### ISSUE TITLE
Running Minecraft With Forge(Modded) issues.(OpenGL Problems?)

### ISSUE THREAD

**Issue by SovietGundam** [jamesstringerparsec/Easy-GPU-PV#103]
Minecraft uses OpenGL. Not officially supported by Easy-GPU-PV
But maybe someone can help?  ¯\_(ツ)_/¯

Getting minecraft vanilla (Unmodded to work) is easy enough.
https://github.com/jamesstringerparsec/Easy-GPU-PV/issues/74
This explains it clearly. Thank you BTW!

However just adding Forge to Minecraft causes it to crash. It seems it starts to boot, then crashes soon after.
I'm using MultiMC, the official launcher just apparently refuses to install.
Here is the Crash log if required: https://pastebin.com/rQty2rNB

**Comment by SovietGundam** [comment]
The latest update of java 8 broke forge compatibility.
After updating java on host, Minecraft also broke on host.
I just recommend installing java 11, solved my issue.

**Comment by Kodikuu** [comment]
This is entirely unrelated to this project
