### ISSUE TITLE
Is it possible to run macos natively using RX 580?

### ISSUE THREAD

**Issue by debjit** [jamesstringerparsec/Easy-GPU-PV#105]
I have this config
Ryzen 1600
B350 MB
16GB Ram
RX 580
Can I run Hackintosh with this script hosted inside windows?

**Comment by Kodikuu** [comment]
This script leverages a Windows-only feature for allowing a guest VM to use a host machine's GPU, so no.

**Comment by debjit** [comment]
Ok. Thank you for clearing.
