### ISSUE TITLE
Has anyone had problems with a kernel error?

### ISSUE THREAD

**Issue by reno911unlocred** [jamesstringerparsec/Easy-GPU-PV#106]
Ok so, the good thing, this issue is consistant for me, so, i install the epic games launcher and try to start installing fortnite (i don't play, that is why the share thing) but, as soon as it starts downloading it freezes, BSOD and this error comes up.

![image](https://user-images.githubusercontent.com/3080187/151279425-d0b78544-ae41-4426-9c79-7f47334acdce.png)

Anyway, it happend with some other thing, i think, trying to install directx (i wanted to make RTSS work (riva tuner statistic server) but it said directx was not installed and i downloaded and tried to install from microsoft but it crashed like this too, but, if I have like, project cars 2 already on a drive an open it i can play just fine. But this error comes up too often, does it have something to do with the TPM bullshit? with the fact that i am on w10 hosting this w11 VM? that my host PC does not have a TPM or enabled as far as i know? what could be the cause?

**Comment by Kodikuu** [comment]
" with the fact that i am on w10 hosting this w11 VM?"

I strongly recommend that you match Windows versions. So run a Windows 10 VM, or upgrade to a Windows 11 host. Differences between the two can matter, for GPU-P

**Comment by Kodikuu** [comment]
You can split Win10, you just can't pick which GPU to split
