### ISSUE TITLE
Where can i get the virtual display drivers and install them manually?

### ISSUE THREAD

**Issue by Manveer-Singh-99** [jamesstringerparsec/Easy-GPU-PV#107]
Since playing on native hardware makes more sense, i want to install the virtual display drivers on the local machine( not vm)

**Comment by jlarisch** [comment]
but, why?

**Comment by Kodikuu** [comment]
Doing so will not provide those displays to the VM.

If you need the virtual displays outside of this, you will need to purchase Parsec Warp, which is what they usually come from
