### ISSUE TITLE
How Do You Change the GPU Allocation of an Existing VM?

### ISSUE THREAD

**Issue by SeriousTyro** [jamesstringerparsec/Easy-GPU-PV#108]
I have allocated 15% of my GPU each for 6 VM instances, however I'd like to change it to 10% each.
How can I do this?

**Comment by Kodikuu** [comment]
Take a look at the `Assign-VMGPUPartitionAdapter` function in `CopyFilesToVM.ps1`

**Comment by LitBomb** [comment]
kind of related.  After you partitioned your GPU, if no longer want to share your GPU with a VM (e.g. don't need to run Parsec any more on the host), do you need to undo the partitioning or does the host computer continue to have 100% of the GPU?  Thanks.

**Comment by Kodikuu** [comment]
The host always has 100%, the guest is just _allowed_ to use the partitioned amount. Even if the VM is running and playing a game, it may not be using the full partitioned amount if the game doesn't need it all. It doesn't work like partitioning disk space, or assigning RAM
