### ISSUE TITLE
Maximum allocation percentage

### ISSUE THREAD

**Issue by cristianrz** [jamesstringerparsec/Easy-GPU-PV#109]
More of a question rather than an issue: what's the maximum GPU allocation? If I just want to use the host as a hypervisor and only log in and do stuff on the guest, can I give it a 90%/100%?

**Comment by Kodikuu** [comment]
You should be able to give 100% without issue. You're not actually passing that over to the VM, simply allowing the VM to access the resource. The host will always take what it needs with priority over the VM, so you'll never really manage to give the VM 100% in practice, but it won't cause issues.

**Comment by cristianrz** [comment]
tried to set 100% and it worked, yes, performance is about 95% of baremetal on some tests done :)
