### ISSUE TITLE
Can't Change VM Resolution

### ISSUE THREAD

**Issue by Ruok2bu** [jamesstringerparsec/Easy-GPU-PV#118]
I installed the same version of Windows 11 on both the host and VM. I also got a display port dongle. I cant change the resolution (its stuck at 10924x768) of the monitor in the VM. With or without the dongle and my monitors on, the resolution picker is greyed out.

My GPU is: EVGA Geforce RTX 2080
And it displays in the VMs device manager.

Any idea how i can fix this?

P.S.  The resolution picker in Parsec itself is also missing.

**Comment by gdias1992** [comment]
What was the solution ?

**Comment by Ruok2bu** [comment]
Not sure, it randomly fixed itself after a few reboots.
