### ISSUE TITLE
Why dont i have write permission

### ISSUE THREAD

**Issue by Teckcheck** [jamesstringerparsec/Easy-GPU-PV#139]
So i decided to check my errors i have with my maschine while copying gpu and audio drivers and its these files 
Imgur.com/a/oR76mCJ
Anyway to force windoes to copy em as i always says (acsess to path "filepath" was denied

**Comment by FlyGuyGo** [comment]
You need to run PowerShell as an administrator.

**Comment by Teckcheck** [comment]
> You need to run PowerShell as an administrator.

Yeah but heres the thing I DID

**Comment by FlyGuyGo** [comment]
> > You need to run PowerShell as an administrator.
> 
> Yeah but heres the thing I DID

Can you confirm which script you are running?

**Comment by Teckcheck** [comment]
I just found out my problem:
So windows has write protected the drives folder so files cant be changed  making the script un usuable unless i had a nvidia card in wich i could copy some files manually

**Comment by gta0gagan** [comment]
> I just found out my problem: So windows has write protected the drives folder so files cant be changed making the script un usuable unless i had a nvidia card in wich i could copy some files manually

How did you solve the issue? I am trying to run the script and its getting failed at :

`Copy-Item : Access to the path 'K:\windows\system32\drivers\portcls.sys' is denied`

**Comment by Teckcheck** [comment]
> How did you solve the issue? I am trying to run the script and its getting failed at :
> 
> `Copy-Item : Access to the path 'K:\windows\system32\drivers\portcls.sys' is denied`

i said before, the file is write protected, as you can see, it says "denied" in the command line, i believe that at the time, i checked the file portcls.sys, and saw it had a write protect on it, so sorry to give your hopes up, but i haven't found a solution myself, and honestly, have given up with further troubleshooting.

**Comment by gta0gagan** [comment]
> > How did you solve the issue? I am trying to run the script and its getting failed at :
> > `Copy-Item : Access to the path 'K:\windows\system32\drivers\portcls.sys' is denied`
> 
> i said before, the file is write protected, as you can see, it says "denied" in the command line, i believe that at the time, i checked the file portcls.sys, and saw it had a write protect on it, so sorry to give your hopes up, but i haven't found a solution myself, and honestly, have given up with further troubleshooting.

No issues. Thanks for the update. I think I have to give up playing games in a virtulaized windows environment. I have spent too much time on this.
