### ISSUE TITLE
Problem playing the game stutter

### ISSUE THREAD

**Issue by xiandoubao** [jamesstringerparsec/Easy-GPU-PV#146]
Virtual machines created with easy-gpu-pv play games stutter, and other scripts are used to virtualize the default virtual machines to play games smoothly

**Comment by Kodikuu** [comment]
Please could you provide a link to a script that sets up GPU-PV VMs that don't stutter for you?

If your issue is with the GPU-PV form of virtualisation itself, that's a Windows GPU-PV issue rather than this script, which simply sets it up a VM with that feature of Windows
