### ISSUE TITLE
weird error "'GPUPV' specifies an upper MMIO region that is above the supported physical address range."

### ISSUE THREAD

**Issue by Flamity** [jamesstringerparsec/Easy-GPU-PV#153]
I have no clue what is happening or what this means (I don't know this kinda stuff) but every time I try to start the virtual machine it says,

"'GPUPV' failed to start. 

The configuration of the virtual machine 'GPUPV' specifies an upper MMIO region that is above the supported physical address range.

'GPUPV' failed to start. (Virtual machine ID
D39289D4-2206-40F8-BB57-6D57C03D35BF)

Virtual machine 'GPUPV' cannot be started. The upper MMIO region (0x00000017dffff000) is above the the supported physical address range. Make sure that the upper MMIO region is below 0x0000001000000000. (Virtual machine ID D39289D4-2206-40F8-BB57-6D57C03D35BF)"

![dngjhsbdgijhsdbg](https://user-images.githubusercontent.com/74884800/164409211-a2541987-31f9-4e7b-afab-791aeeab41b1.PNG)
My PC specs: Intel Core i7 2600, GTX 1050ti, 16gb RAM DDR3

**Comment by Flamity** [comment]
@jamesstringerparsec I don't wanna be irritating but I haven't been able to get this issue to stop at all. The best I got was changing the HighMemoryMappedIoSpace to 512MB. For some reason once I do that, it'll start to boot but it takes forever and when it gets into the desktop the GPU gets error 43 in devices. I really wish I knew what I was doing because this is so hard.

**Comment by Kodikuu** [comment]
I provided an answer in #40
