### ISSUE TITLE
DETECTED HEUR:Trojan.PowerShell.Generic 

### ISSUE THREAD

**Issue by ismaelEfraim** [jamesstringerparsec/Easy-GPU-PV#154]
When trying to download the repo my antivirus goes crazy, telling me there is a high risk. Is it safe?

**Comment by Flamity** [comment]
It's entirely safe don't worry. I don't personally work on this project but basically powershell scripts make your computer execute commands as they are written in the file. So sometimes someone might ask you to download one and run it even though it makes your computer kill itself basically. 

Your anti-virus has no way of knowing if the powershell script will kill it or do something useful so it just blocks the file entirely I assume. You can safely download it on the [official github page](https://github.com/jamesstringerparsec/Easy-GPU-PV).

**Comment by Kodikuu** [comment]
Indeed, all your AV is actually saying is "This is a generic powershell script, I don't like it"
