### ISSUE TITLE
Unauthorized access error 

### ISSUE THREAD

**Issue by uhuhuhuhuhuhuhuh** [jamesstringerparsec/Easy-GPU-PV#157]
File C:\Users\Morgan\Desktop\exps\Easy-GPU-PV-main\PreChecks.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess

PowerShell ISE is spitting this error even though its being ran with admin privileges

**Comment by uhuhuhuhuhuhuhuh** [comment]
nvm found a fix just needed to read https:/go.microsoft.com/fwlink/?LinkID=135170.

**Comment by Borgotto** [comment]
@uhuhuhuhuhuhuhuh you should just take a better read at the README.md
