### ISSUE TITLE
Can anyone confirm Parsec 150-82a is supposed to still work?

### ISSUE THREAD

**Issue by ericwj** [jamesstringerparsec/Easy-GPU-PV#158]
All of a sudden my setup stopped working with error 

    Error [-14003] The host could not capture the screen

All I do is connect from the Hyper-V host to the virtual machine with Parsec installed. I didn't touch anything, so I suspect the latest updates broke it.

Can anyone confirm Parsec 150-82a is supposed to still work? Step 1 would be to just display the Windows desktop.

**Comment by Kodikuu** [comment]
Try uninstalling Parsec and rebooting the VM. After the reboot, one of the scripts set up by this setup script will reinstall Parsec, allowing you to log into it again via the Hyper-V viewer, after which you should reboot the VM once more.

After that, it should start working again. If not, re-open this issue and let me know the contents of `%programdata%/Parsec/config.txt`

**Comment by ericwj** [comment]
No change.

In the Parsec Discord I had a chat with Callum. He blames Windows and sais it can't be fixed. That he would have if he could. I don't know. It's lame. It worked for weeks.

`config.txt`:
```ini
app_channel = release11
app_host_peer_id = AAAAAAAAAAAAAAAAAAAAAAAAAAA
app_run_level = 1
app_changelog_ver = 2
host_virtual_monitors = 1
host_privacy_mode = 1
```
`log.txt`:
```
[F 2022-05-17 13:46:28] ===== Parsec: Started =====
[D 2022-05-17 13:46:28] log: Parsec release11 (150-82a)
[D 2022-05-17 13:46:28] d3d11_ctx_init: 'D3D11CreateDevice' failed with HRESULT 0x80004005
[D 2022-05-17 13:46:28] d3d9_ctx_init: 'Direct3DCreate9Ex' failed with HRESULT 0x8876086A
[D 2022-05-17 13:46:28] supdater_fetch: pservice.exe is up to date
[D 2022-05-17 13:46:28] mty_gl_ctx_create: 'wglGetProcAddress' failed to find 'wglSwapIntervalEXT'
[D 2022-05-17 13:46:28] supdater_fetch: parsecd.exe is up to date
```
Probably that was before rebooting again.
```
[F 2022-05-17 14:26:53] ===== Parsec: Started =====
[D 2022-05-17 14:26:53] log: Parsec release11 (150-82a)
[D 2022-05-17 14:26:53] supdater_fetch: pservice.exe is up to date
[D 2022-05-17 14:26:53] supdater_fetch: parsecd.exe is up to date
[D 2022-05-17 14:27:01] STUN reply from ::ffff:52.86.26.213:3478
[D 2022-05-17 14:27:01] net           = BUD|::ffff:192.168.0.3|31338
[D 2022-05-17 14:27:01] vdd_init: 'MM_Connect' failed with error -1
(...)
[D 2022-05-17 14:39:52] STUN reply from ::ffff:52.86.26.213:3478
[D 2022-05-17 14:39:52] net           = BUD|::ffff:172.25.80.1|31338
[D 2022-05-17 14:39:52] vdd_init: 'MM_Connect' failed with error -1
[I 2022-05-17 14:39:52] Eric#0000000 connected.
[I 2022-05-17 14:39:53] DUPLICATE: E_INVALIDARG
[I 2022-05-17 14:39:53] DUPLICATE: E_INVALIDARG
[I 2022-05-17 14:39:55] DUPLICATE: E_INVALIDARG
[I 2022-05-17 14:39:58] * host_msg_thread_cleanup[1969] = -14003
[I 2022-05-17 14:39:58] Eric#0000000 disconnected.
```
Driver is still listed as 30.0.15.1215 on both machines.

**Comment by montvid** [comment]
Parsec release (150-84b) gives the same error - why is this issue closed? What version of parsec still works? I installed parsec with the script.
`Error [-14003] The host could not capture the screen
`
