### ISSUE TITLE
Powershell script installs Windows 10 pro N, not sure why.

### ISSUE THREAD

**Issue by fretl** [jamesstringerparsec/Easy-GPU-PV#159]
Hey guys,

i got a problem, when i run the powershell script it installs windows 10 pro N, i need the "normal" windows 10 pro, because i got a key for that. how can i prevent that the 10 pro N version gets installed?

thank you!

**Comment by Orjie** [comment]
Hey there,

did you find the reason for Windows N? In my case it's Windows 11 Pro N - games like Call of Duty: Cold War won't run on it :S.

thank you :)

**Comment by nine-2-five** [comment]
It seems to happen in Country specific ISO, in English ISO the Professional edition is 6th in the dropdown, while in my language(EU) it is 7th. The 6th in my language is Windows Pro N.
