### ISSUE TITLE
VM not using hardware acceleration for DX12?

### ISSUE THREAD

**Issue by Schlegsr** [jamesstringerparsec/Easy-GPU-PV#160]
After getting my dual remote user machine up and running, I moved it to the closet, and now the VM will not run in DX12. It worked fine with a local monitor on the host, even when both users were connected remotely, but now that it's headless the VM only seems to run DX12 with no hardware acceleration. I have the HDMI dummy plug that Parsec recommended installed. Heaven runs identically on both machines ~230fps in 1080p Ultra, and the one game I have been trying, Wonderlands, runs fine on the VM in DX11 mode. I am at a loss to figure out what got changed by disconnecting a monitor, I have attached DxDiag from both machines. Any ideas? 

[DxDiagHost.txt](https://github.com/jamesstringerparsec/Easy-GPU-PV/files/8627043/DxDiagHost.txt)
[DxDiagVM.txt](https://github.com/jamesstringerparsec/Easy-GPU-PV/files/8627048/DxDiagVM.txt)

**Comment by Kodikuu** [comment]
Both DxDiag's claim DirectX12 support, but actual capabilities will depend on how GPU-PV itself (Microsoft's Windows feature, not this setup script), the virtual display, the host driver and guest copy of the driver, and chosen application all interact.
