### ISSUE TITLE
Support for Windows 8.1 VM?

### ISSUE THREAD

**Issue by CDSFounder** [jamesstringerparsec/Easy-GPU-PV#162]
Hi,

There are certain games that only run well in Windows 8 that I have been dual booting a PC in order occasionally play them. Is it possible to have the HyperV host be Windows 11 while the guest VM is Windows 8.1? 

Any guidance would be greatly appreciated.

**Comment by Kodikuu** [comment]
The OS versions and GPU drivers must be matched for GPU-PV itself, a Windows feature implemented by Microsoft, to function properly. Windows 8.1 also cannot support our display driver, so there would be no capturable display.

If you're using a Win10 host, it must be a Win10 guest of the same version. The same is true of Win11.
