### ISSUE TITLE
Unable to uninstall Parsec

### ISSUE THREAD

**Issue by kallell** [jamesstringerparsec/Easy-GPU-PV#165]
Any idea how this gets auto installed even after manually uninstalling it? It comes back regardless every time I boot the VM; effectively making it basically malware.

**Comment by Kodikuu** [comment]
Two config files are placed to install Parsec at VM boot and user login to ensure that you can't completely mess up the setup, or break it by accident later on.

Look in the Machine and User sections of the repo.
