### ISSUE TITLE
Host random freeze

### ISSUE THREAD

**Issue by Zoxjib** [jamesstringerparsec/Easy-GPU-PV#167]
I've been using this to run 2 Hyper-V VMs for a few weeks. Every once in a while, the host freezes without any errors and without an obvious reason. If audio was playing it keeps playing, and the mouse can keep moving and the cursor even changes based on what it is on top of at the time, but I can't click or do anything, opening task manager doesn't work, alt+f4 doesn't close anything. The only way out of this is to shutdown/restart the host using the hardware buttons on the case.

**Comment by Kodikuu** [comment]
This is an issue with Microsoft's GPU-PV itself, or how the GPU or it's drivers are handling it, rather than this script.
