### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by quinnlybacon** [jamesstringerparsec/Easy-GPU-PV#169]
Same issue as https://tagmerge.com/issue/jamesstringerparsec/Easy-GPU-PV/25 but restarting PowerShell didn't fix it.

Not sure if it's an issue with the autounattend file or if it's because I'm putting the VHD not on the C drive or what
Here's the transcript that was generated

**********************
Windows PowerShell transcript start
Start time: 20220518190055
Username: DESKTOP-HURNV03\Quinn3600X
RunAs User: DESKTOP-HURNV03\Quinn3600X
Configuration Name: 
Machine: DESKTOP-HURNV03 (Microsoft Windows NT 10.0.19043.0)
Host Application: C:\Windows\syswow64\WindowsPowerShell\v1.0\PowerShell_ISE.exe
Process ID: 14224
PSVersion: 5.1.19041.1682
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.1682
BuildVersion: 10.0.19041.1682
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
INFO   : Opening ISO Win10_21H1_EnglishInternational_x64.iso...
INFO   : Looking for G:\sources\install.wim...
INFO   : Looking for the requested Windows image in the WIM file
INFO   : Image 6 selected (Professional)...
INFO   : Creating sparse disk...
INFO   : Mounting VHDX...
INFO   : Initializing disk...
INFO   : Creating EFI system partition...
INFO   : Formatting system volume...
INFO   : Setting system partition as ESP...
INFO   : Creating MSR partition...
INFO   : Creating windows partition...
INFO   : Formatting windows volume...
INFO   : Windows path (K:) has been assigned.
INFO   : Windows path (K:) took 1 attempts to be assigned.
INFO   : System volume location: J:
INFO   : Applying image to VHDX. This could take a while...
INFO   : Image was applied successfully.
INFO   : Applying unattend file (autounattend.xml)...
INFO   : Making image bootable...
PS>TerminatingError(Start-Process): "This command cannot be run due to the error: The system cannot find the file specified."
>> TerminatingError(Start-Process): "This command cannot be run due to the error: The system cannot find the file specified."
ERROR  : This command cannot be run due to the error: The system cannot find the file specified.
INFO   : Log folder is C:\Users\QUINN3~1\AppData\Local\Temp\Convert-WindowsImage\2cebf702-817c-4b65-8e6d-acb92fadcc40
INFO   : Closing Windows image...
INFO   : Done.
**********************
Windows PowerShell transcript end
End time: 20220518190258
**********************

**Comment by uhuhuhuhuhuhuhuh** [comment]
i have the same issue but it still didnt work for me

**Comment by Abyss-W4tcher** [comment]
Hi, be sure to run the x64 version of Powershell ISE (not x86). If not, the script won't find "bcdboot.exe" or other executables.

**Comment by jamesstringerparsec** [comment]
I added a check for this for future users
