### ISSUE TITLE
GPU-P Not Detecting Changed Device Name (In Device Manager)

### ISSUE THREAD

**Issue by Shaunimsorry** [jamesstringerparsec/Easy-GPU-PV#177]
> System Compatible
Printing a list of compatible GPUs...May take a second
Copy the name of the GPU you want to share...
NVIDIA GeForce RTX 2080 SUPER
NVIDIA GeForce RTX 2080 SUPER
NVIDIA GeForce RTX 2080 SUPER
NVIDIA GeForce RTX 2080 SUPER
Press Enter to Exit: 

In this case how would we use the GPU - NAME tag to set partitions on different GPU'S

**Comment by juanhaywood** [comment]
Same problem. Following for solution.

**Comment by Kodikuu** [comment]
I believe this is a limitation of GPU-PV / Hyper-V. I'm unaware of a way to specify GPUs other than by name
