### ISSUE TITLE
Microphone in a normal session (NO ADVANCED SESSION MODE)

### ISSUE THREAD

**Issue by zChris99** [jamesstringerparsec/Easy-GPU-PV#183]
hi I have a question, I have correctly installed the vb cable driver and it works perfectly but I can't speak to my microphone, could you help me? Is there any way to insert the microphone without having to use the advanced session mode? Unfortunately with that mode there are compatibility problems.

**Comment by Kodikuu** [comment]
Parsec does not support microphone passthrough at this time.
