### ISSUE TITLE
Host soft crash after disconnect

### ISSUE THREAD

**Issue by MrPlayerYork** [jamesstringerparsec/Easy-GPU-PV#189]
Hey all, so I was testing it out and for the most part the script works really well, however I had a few problems with disconnecting from parsec or through hyper-v manager. Most of the time, when I disconnect, my computer screen will freeze up and nothing updates. My mouse moves, sound plays, but thats it. CTRL/ALT/DELETE doesn't work, response time from clicking is uber slow, and sometimes I can't even shutdown the pc (Have to hold the power button instead of just pressing it.) I was wondering if anyone knows whats going on and/or knows a way for me to get debug info about the vm to try and find the problem.

**Comment by mashirooooo** [comment]
I have the same problem

**Comment by SDI-admin-dev** [comment]
You don't need to shutdown your PC to get it back,  just take out your display cable (hdmi or whatever) should then be able to get your PC back from this strange lock state.

**Comment by Kodikuu** [comment]
This is a known issue with Windows Hyper-V's GPU-PV. There is nothing this script can do about it.

**Comment by W1LDC4l2D** [comment]
I also just discovered that using the Windows shortcut to reset your graphics will also fix this issue

Crtrl-Shift+Win+B

**Comment by JamesAndrei-DG** [comment]
Adding another monitor in the guest os like this https://www.amyuni.com/forum/viewtopic.php?t=3030
Somehow fix the issue for me.
