### ISSUE TITLE
Parsec can't use hardware decoding on Win7+AMD HD6570?

### ISSUE THREAD

**Issue by devioa** [jamesstringerparsec/Easy-GPU-PV#191]
My virtual machine configuration is Win11+5900X+6900XT (GPU-PV), and it can be accessed normally on my laptop (Win7+Intel built-in graphics), but not on another desktop computer (Win7+AMD HD6570) access, Parsec reported error code -10 (meaning DECODE_ERR_INIT)
Does anyone have the same situation as me?
Does anyone know how to fix it?

**Comment by Kodikuu** [comment]
This is not an issue with this project.

The HD6570 is a TeraScale GPU, rather than the more modern GCN or RDNA. It's decoder (and encoder, if present) are not compatible.
