### ISSUE TITLE
Download of Windows ISOs is no longer available due to Microsoft having altered their website to prevent it.

### ISSUE THREAD

**Issue by notMarvin123** [jamesstringerparsec/Easy-GPU-PV#193]
The download is no longer available on the website and even with rufus it only gives the error: Download of Windows ISOs is no longer available due to Microsoft having altered their website to prevent it.

The only to get it from Microsoft is to use the media creation tool which only gives an invalid ISO, where can I get the correct ISO file?

**Comment by Swany6mm** [comment]
I just used Rufus (3.20) tonight and it worked fine.

**Comment by 93UN1** [comment]
just use f12 in chrome to simulate an IPhone for example... hope that helped :)
