### ISSUE TITLE
Connect the client computer via IP address or domain

### ISSUE THREAD

**Issue by BeingNoAbility** [jamesstringerparsec/Easy-GPU-PV#194]
First of all, let me express my thanks for all the work you have done! This is a wonderful project, allowing me to share my over-powered RTX3090 with my friend who can't afford to buy a GPU, and I can even game together with her on the same computer!

  But there is a problem. My friend can scarcely connect my computer most of the time. The most common error code is 6023, which indicates that my friend's network might be behind a carrier-grade NAT, and that's something I can't deal with.

  I requested public IP from my ISP long ago and they did, so I have a dedicated IP associated with my own domain. I tried to set up sunshine(an open-source alternative to Nvidia gamestream) on the client, told my friend to connect my computer via the domain I registered, and it worked every time she connected!

  But sunshine is still not as handy as parsec. It allows only one user to connect. A UAC prompt will make it stuck. When there's nothing changing on the display, some tasks will be laggy, like typing in text or just moving the mouse cursor.

  So, I'm wondering if there is a way I can connect the client by parsec via IP address or domain? Thanks!

**Comment by Kodikuu** [comment]
Parsec error 6023 is not an issue with this project, please visit the Parsec Discord or read the 6023 article on the Parsec support website for help with that. I recommend port-forwarding Parsec, and ensuring you're not double-NAT'ing the VM with the virtual network adapter it uses

Slow display mode changes (UAC prompts opening for example) are a known problem with GPU-PV, and there's nothing this script can do about it.
