### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by therepower** [jamesstringerparsec/Easy-GPU-PV#196]
hello,
I use this method to run 2 instances of a game. The game uses like %15-17 cpu on my pc but uses %100 cpu on the VM and has low FPS,
i attached 6 of 16 cores to the VM but the VM consumes %49 of my cpu.

any suggestions to fix this, is this normal behaviour?

i have a i7 11800H with 16 cores and 4 ghz turbo speed and RTX 3080 GPU

**Comment by Kodikuu** [comment]
This is not an issue with the Easy-GPU-PV script, but rather GPU-PV or Hyper-V on Windows, or the game itself
