### ISSUE TITLE
Option to stop parsec reinstallation

### ISSUE THREAD

**Issue by cezarlacatus** [jamesstringerparsec/Easy-GPU-PV#198]
Because Parsec doesnt support RPI 4, I switch to sunshine host.I want to unistall Parsec compleatly.I tried everything but it keeps reinstalling at the vm restart.How do I stop it?

**Comment by sinni800** [comment]
It should be enough to delete everything in side C:\Windows\System32\GroupPolicy to make it stop using the Logon scripts to install parsec

**Comment by cezarlacatus** [comment]
> It should be enough to delete everything in side C:\Windows\System32\GroupPolicy to make it stop using the Logon scripts to install parsec

Didnt know that, thank you.A future release can have a boolean flag in the CopyFiles script that prevents parsec instalation(also this fixes the OpenGl problems in all games that require OpenGl caused by the driver)

**Comment by Movieaholic** [comment]
I tried to to do exactly what you are doing but had problems with sunshine did you get it working correctly in the end?

**Comment by cezarlacatus** [comment]
@Movieaholic do you encounter problems? You need to allow the Host to be Discoverable on the network.Otherwise the ports cannot be seen.

**Comment by Movieaholic** [comment]
i can connect fine just when i start a game it doesn't show video on the ipad I'm streaming to, if i play for a bit in the vm window on the pc sometimes it shows up on the ipad eventually. Also the service script in the tools folder doesn't seem to do anything

**Comment by Movieaholic** [comment]
I was just looking at the script (copy files to vm) and i think if you delete the section Function Setup-ParsecInstall from lines 142-178 it wont install parsec int he first place

**Comment by cezarlacatus** [comment]
> i can connect fine just when i start a game it doesn't show video on the ipad I'm streaming to, if i play for a bit in the vm window on the pc sometimes it shows up on the ipad eventually. Also the service script in the tools folder doesn't seem to do anything

Thats weird...I dont have experience on apple products.They have a discord somewhere...maybe they can help u out
