### ISSUE TITLE
Multi GPU in Win 10...

### ISSUE THREAD

**Issue by 93UN1** [jamesstringerparsec/Easy-GPU-PV#202]
Hey, thanks for this rly nice script :)
Just got one problem: I have 2 gpu's in my system...
I want to pick the stronger gpu to divide it and effectively have 3 machines running. the problem is, that im on win10 (i dont wanna update to win11) and the tutorial says, that i have to leave the gpu name parameter to auto. But which gpu is the script choosing then? Automatically the strongest? Or the one in the first slot? Is there any way to edit the script for my needs without destroying something?

**Comment by Kodikuu** [comment]
The GPU-PV feature of Windows' Hyper-V does not support specifying the GPU at all on Windows 10. This is a limitation of GPU-PV itself on Windows 10, not this script
