### ISSUE TITLE
Select the last listed video card in Windows 10 host PC

### ISSUE THREAD

**Issue by Pucur** [jamesstringerparsec/Easy-GPU-PV#205]
Hi all!

I just want to give some help if somebody struggles with similar issues what i had.
I have 6 GPU in my PC, and I cannot select GPUs in Windows 10, I know it possible to select when you use Windows 11, but my computer is so old, that I cannot enable TPM at all sadly.
So when i run the precheck, these are my VGAs on the list:

> Radeon RX 580 Series
>Radeon RX 580 Series
>Radeon RX 580 Series
>Radeon RX 580 Series
>Radeon RX 570 Series
Radeon RX 570 Series
Radeon RX 570 Series
Radeon RX 570 Series
Radeon RX 570 Series
Radeon RX 570 Series
Radeon RX 570 Series
Radeon RX 570 Series
Radeon RX 570 Series
AMD Radeon RX 6700 XT

Those are my cards, but the GPU-P only works on my newest 6700 XT card.

In the AUTO settings, it selects the first card, so the 580, **BUT**
if you edit the **Add-VMGpuPartitionAdapterFiles.psm1** file and Replace all
`Select-Object -First 1`
to
`Select-Object -Last 1`
and it seemed it will install as 6700 XT, and there was no error in the end messages, but when I started it, it remained as the first showed VGA, the 580.

is it there a way to replace the vga's on the list? I put the 6700 XT into the PCI-Express main slot, and in the Task Explorer it seems as thats the first VGA, even in Device Manager, but in this list for some reason its not the first.

Thanks for all the answers!

**Comment by Kodikuu** [comment]
You could try re-ordering the GPUs physically in your machine, but that's basically your only option.

It's possible to install Windows 11 without TPM, with a little research
