### ISSUE TITLE
Support for 4090 or 4080

### ISSUE THREAD

**Issue by zane-shus** [jamesstringerparsec/Easy-GPU-PV#207]
Does anyone know if this will be supported in the new 4080/4090 announced today?

**Comment by scriptgenerator64** [comment]
I would also like to know this...
I want to buy the 4090 on the condition that it will properly work with GPU paravirtualization

**Comment by Kodikuu** [comment]
Whether or not the 40-series cards work for GPU-PV is not a question for this project. This is just a script that _uses it_. It's the same Nvidia drivers, so nothing needs changing here to make it work
