### ISSUE TITLE
How to revert this?

### ISSUE THREAD

**Issue by Aiku1** [jamesstringerparsec/Easy-GPU-PV#210]
Since I've run this script (unsuccesfully, I will add), I've noticed I can't use FreeSync or DDC/CI settings from my host OS anymore.
Is there any way this script affected that and if so, how to revert this without reinstalling?

**Comment by Kodikuu** [comment]
Remove the VM. That's it.

The script makes zero changes that should impact FreeSync or DDC/CI. If there are any issues like that post-install, it's Hyper-V/GPU-PV itself.
