### ISSUE TITLE
Parsec Error 15000 on RX 6600

### ISSUE THREAD

**Issue by GregB98** [jamesstringerparsec/Easy-GPU-PV#215]
Hypervisor / parsec client OS: WIN 10 PRO 22H2 19045.2006
Hypervisor / parsec client GPU: AMD RX 6600

Virtual PC / parsec host OS:  WIN 10 PRO 22H2 19045.2006

Parsec ver.: Build 150-85c

Hypervisor: Hyper-v

Premise: I used Easy-GPU-PV to set up a vm to stream  games to a laptop so my roommate and I can play together. Currently i am debugging on my own pc to minimalize variables.  Everything worked when the Hypervisor had a Geforce 1050Ti GPU,  which I recently switched for an RX 6600

Problem: Client can move cursor around, type on the keyboard but no encoding/decoding is happening on the top right and after a while .... Error:15000 host device not supported

Things I tried: Redo the entire thing, clean OS install on Hypervisor /parsec client PC, did everything manually following https://www.youtube.com/watch?v=XLLcc29EZ_8 this guide. Copied the entire System32, Syswow directories to the Virtual PC / Parsec Host PC.

**Comment by perfectsine** [comment]
Try Downgrading to  Adrenalin 22.5.1 Recommended (WHQL).

Not sure if this is the same issue I had, but I got a 15000 after upgrading to the Adrenalin 22.10.2 Optional (WHQL) drivers.

**Comment by GregB98** [comment]
This fixed it, thank you VERY MUCH!!!!

**Comment by Danielv123** [comment]
This worked for me as well. I had to use the scripts from https://github.com/grrminator/Easy-GPU-PV to get around a parsec issue with opengl games, and then this to get it working on my 6600xt as well.
