### ISSUE TITLE
Ubuntu 22.04 as a VM?

### ISSUE THREAD

**Issue by jfrgagnon** [jamesstringerparsec/Easy-GPU-PV#223]
Is it possible or will it be possible to use those scripts to use GPU-PV from a Win11 host to an Ubuntu (or other linux distributions) hyper-v VMs ?

I'm using linux server and I would need GPU ressources for some workloads so it would be sooooo great if it would work!! :D 

Thanks!

**Comment by Kodikuu** [comment]
This is outside the scope of this project, but you should consider looking at WSLg with GPU acceleration. I have Ubuntu running with Nvidia GPU access in WSLg
