### ISSUE TITLE
Get-VMPartitionableGpu is deprecated. Please use Get-VMHostPartitionableGpu instead

### ISSUE THREAD

**Issue by jfrgagnon** [jamesstringerparsec/Easy-GPU-PV#224]
It seems that Get-VMPartitionableGpu is not supported anymore.
Powershell return "Get-VMHostPartitionableGpu instead".

Does it change anything? Or, should the scripts have to be rewrite with (_Get/Set_)-VMHostPartitionableGpu instead?!

**Comment by JPVenson** [comment]
Get-VMHostPartitionableGpu is not available on W10

**Comment by jamesstringerparsec** [comment]
Not sure where this comment comes from, I don't use `Get-VMPartitionableGpu `
