### ISSUE TITLE
Bypass VM detections by changing cpuid hypervisor bit

### ISSUE THREAD

**Issue by jimmyhlyu** [jamesstringerparsec/Easy-GPU-PV#226]
Is there any way we could modify the hypervisor bit in order to bypass those VM detections? 
This is simple in VMware setting "hypervisor.cpuid.v0 = "FALSE"" in the vmx file.
But not sure how to do it in Hyper V.

**Comment by scriptgenerator64** [comment]
I second this, makes GPU-PV unusable for most of my games

**Comment by jamesstringerparsec** [comment]
This is not possible in Hyper-V

**Comment by mxdh** [comment]
Enable Hyper-V in the Guest OS
Since Hyper-V also sets the cpuid hypervisor bit, this can trick many games, such as the Genshin Impact

**Comment by scriptgenerator64** [comment]
Interesting, I'll be sure to test it out! One particularly pernicious game I want to get working under GPU-PV is VRChat after their latest "security update"

**Comment by mxdh** [comment]
> Interesting, I'll be sure to test it out! One particularly pernicious game I want to get working under GPU-PV is VRChat after their latest "security update"
> 
> UPDATE: No dice on VRChat, but it may be because I am using an AMD processor with a Windows 10 host and thus am unable to perform nested virtualization or enable the full Hyper-V platform in a Hyper-V VM

Easy-GPU-PV does not enable nested virtualization for Win10 on AMD platforms

https://github.com/jamesstringerparsec/Easy-GPU-PV/blob/fb295b0119c52cd0d283d6451d83bb80509e32d0/CopyFilesToVM.ps1#L4380

But with reference to https://techcommunity.microsoft.com/t5/virtualization/amd-nested-virtualization-support/ba-p/1434841, maybe it is possible to make it?

**Comment by scriptgenerator64** [comment]
It is an artificial limitation by Microsoft (https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/nested-virtualization#prerequisites)... I'll test things out again once I get around to migrating to Windows 11

**Comment by scriptgenerator64** [comment]
I finally got around to testing it, no change sadly... VRChat's implementation of EAC makes Hyper-V a non-option for now... if only there was a way to edit the .vmcx binaries directly to trick the OS into thinking that the virtualized hardware is physical

**Comment by Bluscream** [comment]
Any news on this?
I would love to get vrchat working in a VM so i can have my friend use my gpu for playing while i use my pc aswell just with half the resources
