### ISSUE TITLE
problem mount disk-image error

### ISSUE THREAD

**Issue by Kaitenn-dev** [jamesstringerparsec/Easy-GPU-PV#233]
![Screenshot_2 png cdeaa7efb7157122e7f6b92d04653b79](https://user-images.githubusercontent.com/97636170/206829676-2aad21cd-520f-42d9-be53-35d5a34e1368.png)
I don't know why?

**Comment by jamesstringerparsec** [comment]
Your path is probably not correct. I added better checking if you redownload the script.

**Comment by Kaitenn-dev** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/97636170/209479763-0956f988-ab04-4e5d-b059-f0ba44d873bc.png)
![Screenshot_2](https://user-images.githubusercontent.com/97636170/209479769-2e642577-a19e-4846-9ba0-5f8e3fa0b177.png)
same problem ;(

**Comment by Kaitenn-dev** [comment]
I try to multiple place is the same problem
