### ISSUE TITLE
OpenGL works fine but not Vulkan

### ISSUE THREAD

**Issue by jacky400** [jamesstringerparsec/Easy-GPU-PV#240]
OpenGL works fine in basic mode but vulkan is not.

Vulkans works in enhanced mode but haven't artifact.

**Comment by Poltergeisen** [comment]
![image](https://user-images.githubusercontent.com/44731113/213774243-e61198f9-585d-4595-a8c4-521c67776007.png)
in the docs it explains that vulkan will not work. It's a limitation of this technology

**Comment by simonlsp** [comment]
#342 
I have found the workaround about vulkan and opengl.
