### ISSUE TITLE
Driver Update Version

### ISSUE THREAD

**Issue by TwoBe3rs** [jamesstringerparsec/Easy-GPU-PV#243]
Hello,

I wanted to update the driver of the NVIDIA graphics card on the VMs. The latest version is installed on the host. I ran the script accordingly. However, a driver from 2006 (probably the native driver) shows up in the VMs.
I had seen in the script that the INF file is transferred from the host to the mounted VM disk. The INF file contains the device ID of the graphics card from the host. On the VMs ID is different due to the passed graphics card.
So my question:
Is this behavior normal? If so, how can I determine which driver version the VMs are currently running?

Regards

**Comment by Elegantwolf** [comment]
I have the same issue. Moreover, some of my apps wont work and report like:"0xffffffff Memory Could Not Read". I believe that is a graph driver problem.

**Comment by Kodikuu** [comment]
If you're successfully connecting with Parsec, you can ignore pretty much anything else.

Game issues are a separate matter. Some just don't like GPU-PV. There's nothing Parsec or this script can do about that.
