### ISSUE TITLE
Mouse not focused

### ISSUE THREAD

**Issue by LeLaboDuGame** [jamesstringerparsec/Easy-GPU-PV#244]
Hello i'm new with VM, I have try to create a windows 10 vm in Hyper V but when I tried to play at a game my mouse is not focused (she can go outside hyper v)
Do you how to fix ?
Thanks advanced and sorry for my english ^^

**Comment by Kodikuu** [comment]
You can enable Immersive Mode in Parsec, on the PC (not the VM) to have it lock the mouse to the Parsec Window.

I do hope you're using Parsec to play your games, and not the Hyper-V Viewer

**Comment by LeLaboDuGame** [comment]
Hello thank for you message.
I have a problem with parsec. I explain, when I try to connect my local computer (not the vm) to the parsec of the vm, a error message appear and the screen share doesn’t start !
I tried everything but I don’t how to fix.
Thank you again

**Comment by Kodikuu** [comment]
That is unrelated to this issue.
