### ISSUE TITLE
Hyper-V Server 2019

### ISSUE THREAD

**Issue by haifisch88** [jamesstringerparsec/Easy-GPU-PV#245]
Hello, not really an issue but there don't seem to be any other ways to post a question. Does this work on Microsoft Hyper-V Server 2019? Thank you

**Comment by itsTyrion** [comment]
why don't you just try it?

**Comment by haifisch88** [comment]
> why don't you just try it?

Thank you for your useful answer. I havent tried yet because I dont have a gpu. Gpus dont grow on trees and I dont want to shell out for one without knowing that it would work. But its okay then my next question is about what the cheapest used card required for gpu-p to work is?

**Comment by itsTyrion** [comment]
Be more passive aggressive about things I _cannot_ know, I assumed you have _some_ dGPU (Or Intel iGPU) already. 

Do you have Win Server 2019? Win10/11 Pro works perfectly fine. I've read mixed things about GPU-P working in Server 2019.

Any still supported nvidia GPU/Intel iGPU should work. AMD is supported but can be hit-or-miss with parsec with some driver versions.
My GTX 1070 works, I can test if a 750Ti does with Win10 Pro (and maybe with a Server 2019 trial if I find a working spare drive).

**Comment by haifisch88** [comment]
Thanks for your reply, I didn't mean to be rude. I am concerned about Hyper-V Server 2019 and not Windows Server 2019 actually. I have also little interest in parsec and gaming, I just like to know if GPU-P would work under Hyper-V Server. If you have a 750Ti lying around and could test it with Hyper-V Server that would be great!

**Comment by itsTyrion** [comment]
@haifisch88 soooo bad news. I wasn't able to get it to pass through my 1070 and my 750Ti seems to have died for no reason.
On Windows 10 Pro/Enterprise, it works (with near-native performance)

**Comment by haifisch88** [comment]
Thank you for testing it out, you just saved me (and probably a bunch of other people) a couple hundred bucks.
