### ISSUE TITLE
Parsec no longer supports Raspberry Pi 4

### ISSUE THREAD

**Issue by tf-anguskong** [jamesstringerparsec/Easy-GPU-PV#249]
This isn't an issue necessarily with the code, but I would LOVE an option in the PowerShell script to choose between Parsec and NVIDIA GameStream enabled on the VM. This would allow me to use Moonlight on the Raspberry Pi 4s as Parsec dropped support for ARM based operating systems (at least that's the error when I attempt to install the .dbm on the Pi). 

Unfortunately this would require that you are passing through a Nvidia GPU, I haven't gotten the physical hardware to try to do this manually yet. I'm hoping NVIDIA control panel will work without issue, Hopefully will all be here tomorrow and will update the issue with my own notes accordingly.

**Comment by Kodikuu** [comment]
To my knowledge, NVIDIA GameStream is being deprecated.
Even so, assuming it even _works_ in a GPU-PV VM, there doesn't need to be a toggle, you can just use it.

If the lack of a display is an issue, there's nothing the script can do about that. The displays Parsec uses are tied to the Parsec stream itself, and can't be spun up outside of a Parsec stream
