### ISSUE TITLE
Warning: Only Windows 10 20H1 or Windows 11 is supported

### ISSUE THREAD

**Issue by Retrogaymer** [jamesstringerparsec/Easy-GPU-PV#252]
Hi I'm getting the error above when running prechecks.ps1 in ISE Powershell. I realized that windows 10 home on my host machine doesn't work with this, is there any way to do it so this edition can work or is it not possible?

**Comment by Kodikuu** [comment]
To my knowledge, Home editions do not have Hyper-V, so cannot spin up VMs

**Comment by Retrogaymer** [comment]
I found a way to do it, look at the thread here https://www.reddit.com/r/HyperV/comments/111nokj/how_to_allow_hyper_v_to_use_my_5700xt_gpu_for/

**Comment by Retrogaymer** [comment]
> To my knowledge, Home editions do not have Hyper-V, so cannot spin up VMs

Actually I just found out that you can by downloading a script. Also found that the prechecks.ps1 script is essentially useless to run on windows 10, you can skip it and just continue with the next step.
