### ISSUE TITLE
Multiple GPUs (nvidia/intel) on Host, not able to partition intel iGPU

### ISSUE THREAD

**Issue by alex8654** [jamesstringerparsec/Easy-GPU-PV#254]
I'm trying to partition the iGPU to a VM due to Intel Quicksync, but every time I try to partition the Intel iGPU, the nvidia card ends up partitioned on the VM. I used the right name on the script to reflect the GPU I want to configured, still every time it only assigns the Nvidia GPu instead.

Any thouights?

**Comment by Kodikuu** [comment]
Windows 10 cannot specify the GPU to use. Windows 11 can. This is a limitation of GPU-PV, not this script

**Comment by alex8654** [comment]
I forgot to mention I use Windows 11 21H2, so in theory I should be able to pick which one to use. I can list the 2 devices as well in PowerShell
