### ISSUE TITLE
Good performance on DirectX 12, terrible performance on DirectX 11

### ISSUE THREAD

**Issue by mebezac** [jamesstringerparsec/Easy-GPU-PV#257]
I created a Windows 11 Pro VM with Hyper-V using this repo (and also tried with [this fork](https://github.com/grrminator/Easy-GPU-PV)). My host is 64GB DDR5 6000, Ryzen 9 7900x, Nvidia RTX 3070 Windows 11 Pro. I gave the host 50% of the RAM, CPU, and GPU.

When I play a DirectX 12 game, the performance is as expected. However, when I try to play a DirectX 11, the performance is terrible and it seems like the GPU isn't being utilized for some reason.

I discovered this because God of War ran just fine in the VM (\~60fps 1080p high), however a really light-weight game (Season) ran terribly (\~20 FPS 1080p low). I narrowed it down to the biggest difference between the games being the fact that GoW is using DirectX 12 and Season is using DirectX 11.

To illustrate this, here are some screenshots from Fortnite, which helpfully lets you switch between DirectX 12 and 11.

DirectX 12: High 1080p, 120fps cap: [https://i.imgur.com/oOsJF5x.jpg](https://i.imgur.com/oOsJF5x.jpg)

\- Game runs fine, consistently \~120fps

DirectX11: High 1080p, 120fps cap: [https://i.imgur.com/di5M1li.png](https://i.imgur.com/di5M1li.png)

\- Gave up after 5 minutes of the game at 0-1 FPS just trying to render the menu, couldn't even get in the game.

I've tried googling this issue and haven't been able to find anything. Has anyone had this issue, and if so, do you have any idea how to solve it? Thanks!

**Comment by mxdh** [comment]
I also have this problem
https://github.com/jamesstringerparsec/Easy-GPU-PV/issues/221#issuecomment-1406179723

**Comment by mebezac** [comment]
Ah, didn't find that issue when I was searching for some reason, I'll close this one and jump in on that one to help troubleshoot.
