### ISSUE TITLE
Host bluescreen after some time running the vm

### ISSUE THREAD

**Issue by Crussade** [jamesstringerparsec/Easy-GPU-PV#261]
Hello,

i just setup the vm like described in the manual. I am getting either direct blue screen if im not connected via. parsec or i get a fragmented picture if the host crashes while im connected via. parsec. 

Specs:
Windos 10 Pro 22h2 on Host and VM
CPU: Ryzen 7 5800X
GPU: Nvidia Gefroce 3080
GPU Driver: 531.29

i alredy tried setting up everything new. no change at all.
also tried to roll back one GPU Driver. no change. still running the rollback version.
are ther any logs i can post?

**Comment by Crussade** [comment]
Okay did the complet reinstall. looked fine untill i tried to install modded minecraft. is there a chance that java causes this?

**Comment by MysticalWisdom** [comment]
@Crussade I had the same problem, the same way. minecraft worked fine endlessly until I installed OverWolf, which im guessing your modded mc uses too. The overwolf is the problem, modded mc works but you can't use anything with overwolf; causes a BSOD on host after overwolf starts up. I'd download everything you need on the host pc then just bring it over and install the mods manually; can confirm that has been working flawlessly.  I know nothing of "Why" it causes it sadly.

**Comment by Crussade** [comment]
@MysticalWisdom Thank you very much finaly it works. Now my friend can join playing on my pc.
