### ISSUE TITLE
GPU driver errors

### ISSUE THREAD

**Issue by Pro2Player** [jamesstringerparsec/Easy-GPU-PV#282]
Every time i try to run minecraft (no mods) it says that driver not works with OpenGL. I have rtx 3060 12GB and r5 5600. I am using also win11. I try updating driver with script you made but i don't help. I can see my GPU in devices manager but not in task manager

I made a vm 3 Times and every time, thinking i am doing somting wrong and change some values. I sitll don't know what i am doing wrong

**Comment by mitchellurgero** [comment]
OpenGL support is spotty at best due to how Hyper-V passes the GPU through. This link is in the readme and says it may help but doesn't promise anything: https://www.microsoft.com/en-us/p/opencl-and-opengl-compatibility-pack/9nqpsl29bfff?SilentAuth=1&wa=wsignin1.0#activetab=pivot:overviewtab

**Comment by VincyChannel** [comment]
If you disable the Hyper-V Monitor OpenGL doesn't work anymore, make sure you have the Hyper-V and Parsec monitors enabled going in the windows display settings
