### ISSUE TITLE
Host occasionally locking up.

### ISSUE THREAD

**Issue by GlitchedFolx** [jamesstringerparsec/Easy-GPU-PV#294]
Hey everyone!

Hope you're all well.

I have spilt my system into two, one being a VM for my team's video editor, (her laptop is terrible), and the other being my main system. 

I've been having this issue where my system will lock up, everything becomes unresponsive but I can still move the mouse, while my video editors VM is still running fine with no issues.

System specs:
Ryzen 7 5800x
GeForce RTX 3090
32gb 3200mhz DDR4 Memory
Around 3tb spilt across 3 ssds

VM specs:
4 logical cores assigned to vm
30% GPU partitioned to vm
12gb allocated to vm
256gb storage, stored as a single file on SATA ssd

All help is appreciated

Thanks,
GlitchedFolx

**Comment by Kodikuu** [comment]
Welcome to GPU-PV, this is normal.

Use Shift+Ctrl+Win+B to reset your graphics driver on the host. This will likely break the VM's access to the driver.

Windows Hyper-V's GPY-PV feature works by having the host OS carry out tasks for the guest OS, the guest OS never actually has a GPU. It's not the most stable thing in the world, so you should expect issues like this to be fairly common

**Comment by vadash** [comment]
Btw you cant partition GPU

    $factor = 0.25 # 0.25 = 25% of max
    Set-VMGpuPartitionAdapter -VMName $vm -MinPartitionVRAM ($gpu.MinPartitionVRAM) -MaxPartitionVRAM ($gpu.MaxPartitionVRAM) -OptimalPartitionVRAM ($gpu.OptimalPartitionVRAM) -MinPartitionEncode ($gpu.MinPartitionEncode) -MaxPartitionEncode ($gpu.maxPartitionEncode * $factor) -OptimalPartitionEncode ($gpu.OptimalPartitionEncode * $factor) -MinPartitionDecode ($gpu.MinPartitionDecode) -MaxPartitionDecode ($gpu.MaxPartitionDecode * $factor) -OptimalPartitionDecode ($gpu.OptimalPartitionDecode * $factor) -MinPartitionCompute ($gpu.MinPartitionCompute) -MaxPartitionCompute ($gpu.MaxPartitionCompute * $factor) -OptimalPartitionCompute ($gpu.OptimalPartitionCompute * $factor)

will still let VM claim all VRAM

run same winver and host and guest and use parsec to access it. Thats best you can do
