### ISSUE TITLE
Post install first start stuck black screen

### ISSUE THREAD

**Issue by vaio2005** [jamesstringerparsec/Easy-GPU-PV#302]
Hello, I've been trying to run this GPU-PV thing for a while. I had successfully managed to add a GPU to an existing VM, but it resulted in error 43.
I've decided to start fresh, just in case I did something wrong.
I used this script and did everything it told me to do. 
As of now, the VM is stuck on a black screen with the Hyper-V logo and the rotating dots. They can do about one rotation, then immediately stop and freeze. The VM appears to be completely dead after that.

Is there anything I could try to make this work?

**Comment by mitchellurgero** [comment]
What are your specs? GPU? Driver Version?

**Comment by vaio2005** [comment]
I've ended up using VMWare with 3D acceleration enabled.
It's apparently the only system that reliably works on a laptop, like in my case.
