### ISSUE TITLE
Revert GPU splitting?

### ISSUE THREAD

**Issue by Vidares1** [jamesstringerparsec/Easy-GPU-PV#308]
Ehm can someone tell me how to revert the splitting of my GPU? Want to go back to normal cuz I think it may be causing some of my games to crash?

Edit: I know that it wont influence my system and that i can use 100% of my GPU but still want to remove the "copy" in the task manager

**Comment by mitchellurgero** [comment]
If the VM is off it's not splitting the GPU - you can revert but deleting the VM or uninstalling Hyper-V Services.

**Comment by Vidares1** [comment]
Already did both steps but in the task manager it's still "split". I know that I get 100% performance for my main machine, it's just a visual/logistic problem inside the Taskmanager.

**Comment by Kodikuu** [comment]
"copy" is not the split

**Comment by Vidares1** [comment]
Mhmmm ok how can I remove the "copy" pls then :D?

**Comment by Kodikuu** [comment]
You don't need to. It does nothing

**Comment by Vidares1** [comment]
Yeah but just for the esthetics :/? Any easy way?

**Comment by Kodikuu** [comment]
You don't actually have an issue with the GPU-PV script, so I'm closing this.

**Comment by mitchellurgero** [comment]
> Mhmmm ok how can I remove the "copy" pls then :D?

"Copy" has been there since always and will always be there - it's not PV related. Also, it's a function of the card. You should try to leave it alone.
