### ISSUE TITLE
Increasing GPUResourceAllocationPercentage post creation?

### ISSUE THREAD

**Issue by GrelochBart** [jamesstringerparsec/Easy-GPU-PV#312]
Hey folks,

Is there a way to change the GPUResourceAllocationPercentage post the VM creation? If so, how do I do that?

**Comment by devioa** [comment]
same question

**Comment by devioa** [comment]
> same question

https://github.com/jamesstringerparsec/Easy-GPU-PV/issues/280#issuecomment-1530466531

**Comment by GrelochBart** [comment]
$VMName = "GPUPV"
$GPUResourceAllocationPercentage = 30
[float]$devider = [math]::round($(100 / $GPUResourceAllocationPercentage),2)
Set-VMGpuPartitionAdapter -VMName $VMName -MinPartitionVRAM ([math]::round($(1000000000 / $devider))) -MaxPartitionVRAM ([math]::round($(1000000000 / $devider))) -OptimalPartitionVRAM ([math]::round($(1000000000 / $devider)))
Set-VMGPUPartitionAdapter -VMName $VMName -MinPartitionEncode ([math]::round($(18446744073709551615 / $devider))) -MaxPartitionEncode ([math]::round($(18446744073709551615 / $devider))) -OptimalPartitionEncode ([math]::round($(18446744073709551615 / $devider)))
Set-VMGpuPartitionAdapter -VMName $VMName -MinPartitionDecode ([math]::round($(1000000000 / $devider))) -MaxPartitionDecode ([math]::round($(1000000000 / $devider))) -OptimalPartitionDecode ([math]::round($(1000000000 / $devider)))
Set-VMGpuPartitionAdapter -VMName $VMName -MinPartitionCompute ([math]::round($(1000000000 / $devider))) -MaxPartitionCompute ([math]::round($(1000000000 / $devider))) -OptimalPartitionCompute ([math]::round($(1000000000 / $devider)))
