### ISSUE TITLE
Unable to update GPU drivers for VM with more than one drive

### ISSUE THREAD

**Issue by gitinit263** [jamesstringerparsec/Easy-GPU-PV#318]
When I run the updater to update my Grahpics Card Drivers I'm encountering the following error message with a similar error recurring multiple times before Dismounting and saying Done. I think it could be because my VM has two drives (F and H) but don't know how to resolve the issue, is there a way to manually update the VM's graphics card drivers or do I need to edit something with the updater?

My initial input: 
PS C:\Users\pc\Downloads\Easy-GPU-PV-main\Easy-GPU-PV-main> .\Update-VMGpuPartitionDriver.ps1 -VMName GPUPVM1 -GPUName AUTO

Powershell:
Mounting Drive...
Copying GPU Files - this could take a while...
INFO   : Finding and copying driver files for NVIDIA GeForce RTX 3080 to VM. This could take a while...
New-Item : Cannot find drive. A drive with the name 'F H' does not exist.
At C:\Users\pc\Downloads\Easy-GPU-PV-main\Easy-GPU-PV-main\Add-VMGpuPartitionAdapterFiles.psm1:29 char:1
+ New-Item -ItemType Directory -Path "$DriveLetter\windows\system32\Hos ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (F H:String) [New-Item], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.NewItemCommand

Copy-item : Cannot find drive. A drive with the name 'F H' does not exist.
At C:\Users\pc\Downloads\Easy-GPU-PV-main\Easy-GPU-PV-main\Add-VMGpuPartitionAdapterFiles.psm1:36 char:17
+ ...             Copy-item -path "$ServiceDriverDir" -Destination "$Servic ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (F H:String) [Copy-Item], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

**Comment by mitchellurgero** [comment]
I would shutdown the VM, remove the 2 extra drives, update GPU, add the drives back - VM will never know.

**Comment by gitinit263** [comment]
I was going to follow your suggestion and it led me to finding the problem.

I had previously extended the volume and been confused about why it showed as a second drive in the system and figured id just misconfigured the second volumes directory and decided to live with it, when i mounted the virtual disk i only saw the second drives contents and could never find the first drive in hyper v manager or anywhere else. After your comment i decided to finally try and hunt it down to fix it. After a bit of investigation i figured it out:

Extending the virtual hard disk had expanded the drive and the VM had just made it a second partition. Deleting the partition and expanding the original partition resolved the issue and allowed me to run the updater.
