### ISSUE TITLE
Nvidia-SMI and other ramblings

### ISSUE THREAD

**Issue by pilonull** [jamesstringerparsec/Easy-GPU-PV#32]
Hi,

I'm sure you're going to get a ton of influx of activity here due to LTT's recent video, hope you don't mind me adding to that chaos..

OS: Windows 10 21H2
GPU: RTX 3080TI
CPU: intel 8700k (5 of 12 cores allocated to guest)
RAM: 32gb with 16 going to guest

A few things I've been wondering/playing with...

1. nvidia-smi
On the host OS, running nvidia-smi yields this:
![image](https://user-images.githubusercontent.com/8344590/148708429-ff358a96-8c5b-477e-a0d6-7a9115834e6c.png)

PID 15324 is parsec running on the host OS.
PID 1300 is dwm.exe

On the guest OS: 
![image](https://user-images.githubusercontent.com/8344590/148708911-398b36ce-0ef1-4396-b781-dab4fe7a4293.png)

I'm wondering why there are several entries for "Insufficient Permissions" on the host OS, and on the guest OS it is erroring out. It says "No running processes" even when there is a 3d app running. 

The whole thing DOES seem to be working acceptably though.. although, that brings me to my next "issue"

2. GPU utilization stays around 40% on the host despite having set "GPUResourceAllocationPercentage = 50" 
Also, Task Manager on the guest OS does not have a GPU listed there, is that functioning as designed? I'm not supposed to see the host's GPU there, correct? 

3. Do you think there would be any benefit to rolling my driver back in order to use this patch: https://github.com/keylase/nvidia-patch/tree/master/win for patching nvfbs and nvenc to remove those limitations? 

4. For updating when there are changes to your github, is there a way to re-run the script without completely rebuilding the entire VM? Or is just running "Update-VMGPUPartitonDriver.ps1" for driver updates only sufficient? 

5. Would it be worth it to upgrade to windows 11, as far as performance and features are concerned in regards to this project? 

Thanks for such a cool script and all your work!

**Comment by pilonull** [comment]
Also, another question, is it possible to change GPUResourceAllocationPercentage and not have to rebuild the entire VM?

**Comment by jamesstringerparsec** [comment]
The guest OS doesn't use an NVIDIA driver and thus doesn't have access to NVIDIA tools such as nvidia-smi.  The Guest uses a Microsoft driver that passes the graphics calls it receives to the host GPU.

2. At a certain point the OS just does what it wants it seems, the settings we give it are just ballparks for how it should behave.

3.  I don't know if those older patched drivers work with this technology

4.  Yes, that's all you need to run when updating your graphics driver on the host.

5. Windows 11 gives the ability to select the gpu you give to the vm when you have more than 1 gpu, not sure of any other benefits.

6. Not yet, I may add some ability to modify it.
