### ISSUE TITLE
This does not work with Windows 10 Education

### ISSUE THREAD

**Issue by wpopelier** [jamesstringerparsec/Easy-GPU-PV#35]
For those who don't know:  Windows 10 Education builds on Windows 10 Enterprise and provides the enterprise-grade manageability and security desired by many schools.
As an educator I have access to Windows 10 Education version of Windows 10 and probably 11 but this script only works with Pro or Enterprise (what Education is based on).  Any chance the script can be changed so I can run this and maybe showcase in class to my students?

**Comment by asurania** [comment]
Just change line 18 on the PreChecks.ps1 .     You can Change the word Professional or Enterprise to "Education"
if ($build.CurrentBuild -ge 19041 -and ($($build.editionid -like 'Professional*') -or $($build.editionid -like 'Enterprise*'))) {

**Comment by wpopelier** [comment]
Thx will doorgaat tomorrow.  Appreciate the feedback and good work.

**Comment by nikita-tomilov** [comment]
Hi @wpopelier, it seems that it can work on Education edition of Windows - take a look at the referenced issue.
