### ISSUE TITLE
closing SteamVR causes BSOD on host PC

### ISSUE THREAD

**Issue by ericytsang** [jamesstringerparsec/Easy-GPU-PV#364]
it was really awesome that I was able to play VR on the guest VM while my friend was playing VR on the host PC so we could play co-op VR games together.

ran into an annoying problem, but not a blocker.

I get this BSOD on the host PC (not guest VM) when exiting SteamVR only after a headset was connected on the guest VM. I tried exiting normally, ending task from task manager, or turning off the vm from Hyper-V Manager, but all lead to BSOD
![IMG_20240401_225021.jpg](https://github.com/jamesstringerparsec/Easy-GPU-PV/assets/5971684/a83023f5-dc7b-49b3-8422-32cc364152d8)

repro steps:
1. on Hyper-V VM, launch ALVR
2. on Hyper-V VM, launch Steam VR
3. on VR headset (Meta Quest 2 / 3), launch ALVR
4. connect the ALVR on VR headset (Meta Quest 2 / 3) with the ALVR on the Hyper-V VM
5. on VR headset (Meta Quest 2 / 3), close/quit ALVR
6. on Hyper-V VM, close/quit ALVR
7. on Hyper-V VM, close/quit Steam VR
8. on host PC, observe blue screen of death appear

I had this BSOD happen like 10+ times, but my computer still seems to run just fine afterwards.

**Comment by ericytsang** [comment]
> it was really awesome that I was able to play VR on the guest VM while my friend was playing VR on the host PC so we could play co-op VR games together.

setup steps:
1. updated my GPU drivers to the latest available by visiting vendor's site, and downloading manually
2. use [Easy-GPU-PV](https://github.com/jamesstringerparsec/Easy-GPU-PV) to create a new VM
3. in guest VM, install Steam, VR games, SteamVR, and , [ALVR](https://github.com/alvr-org/ALVR) (because Virtual Desktop Streamer doesn't work)
4. on host PC, install Steam, VR games, SteamVR, and , Virtual Desktop Streamer (i personally like VD better, but ALVR probably works too)
5. play games!

if you also want to do this too, then here are details about my setup:
1. GPU: NVIDIA GeForce RTX 3080
6. on guest VM:
    * installed the following: Steam, VR games, SteamVR, [ALVR](https://github.com/alvr-org/ALVR) (because Virtual Desktop Streamer doesn't work) 
    * FYI, this only seemed to work with some games. had some glitches with games like Inside the Backrooms... and Phasmophobia. it seems like updated the GPU drivers to the latest on the host before creating the VM helped a little, but some games are still glitchy.
7. on host PC:
    * installed the following: Steam, VR games, SteamVR, Virtual Desktop Streamer (ALVR would probably work too, but i didn;t try it. because i like VD better)

**Comment by ericytsang** [comment]
i will try comment #304 and update

**Comment by ericytsang** [comment]
> i will try [comment on issue #304](https://github.com/jamesstringerparsec/Easy-GPU-PV/issues/304#issuecomment-1670572182) and update

after trying this solution, BSOD is still showing.

i wanted to share a new finding, though:

1. before applying the `nvlddmkm.reg`, the game "Inside the backrooms" would not start up in VR (screen turns black as game initializes, but then game crashes)
2. after applying the `nvlddmkm.reg`, the game "Inside the backrooms" would not start up in VR (screen doesn't even turn black. it just crashes immediately, it looks as if the game did not even start)
3. i opened `nvlddmkm.reg` in notepad, and "find + replaced" ever occurrence of "DriverStore" with "HostDriverStore" then imported it into the "Registry Editor" again.
4. ran the game again. this time, the game started up!!! nice :D some textures were missing
5. i went into the video settings, and changed the texture setting to "streaming" and then pressed "apply" and then the game froze and crashed
6. upon starting the game up again, it loaded fine, and textures are present as well. wow! can't wait to play with my buddies together.

maybe what i did in step 3 could help others

**Comment by ericytsang** [comment]
For the game "inside the backrooms"... I'm no longer sure if i fixed it by replacing "DriverStore" with "HostDriverStore" in the red file, or if it was fixed by launching the game in PC mode, then lowering the video settings, and turning on the "streamed textures" setting, and then launching the game in VR mode. I had to do both to finally make it work in a new VM.

**Comment by sschamp** [comment]
Same thing happens over here.
As soon as I launch VR Desktop -> Insta Crash on Host.
With ALVR, it crashes only after shutting down the game.

Tried all fixes mentioned above, as well as disabling Resizeable BAR and enabling SR-IOV.
All to no avail.

**Comment by ericytsang** [comment]
Thank you, your workaround worked!

After changing this setting, I am no longer getting anymore BSOD when closing SteamVR/VD/VM 😃

**Comment by sschamp** [comment]
Update, Windows 11 24H2 Insider Preview (Dev channel) with latest NVIDIA drivers use WDDM 3.2 instead of WDDM 3.1
Which fixes many of these memory issues.
