### ISSUE TITLE
the host isn't sending any video data

### ISSUE THREAD

**Issue by AldoGamez89** [jamesstringerparsec/Easy-GPU-PV#383]
Fresh install
I try to  control the VM through parsec, and I get this : 
![image](https://github.com/jamesstringerparsec/Easy-GPU-PV/assets/174545517/6069b168-88a7-4abe-8337-2c40217b83c4)

this  freezes the VM I cannot move a thing or see anything other than a frozen image on the VM

and when I disconnect from parsec , it locks the VM into the sign in image
![image](https://github.com/jamesstringerparsec/Easy-GPU-PV/assets/174545517/f6de28cd-8c0f-42bb-a042-120999b4bf13)

this is a fresh install,  which I've installed 3 times thinking I  messed up something... I even downloaded PASSMARK (on the first install) and confirmed the video drivers were installed correctly..

so I'm stuck 

Device manager shows 3 devices, not sure if it's relevant.

Been using parsec for years now, no clue what's wrong.

**Comment by AldoGamez89** [comment]
I finally found the log file 
![image](https://github.com/jamesstringerparsec/Easy-GPU-PV/assets/174545517/9de06937-8f63-4423-a86e-fc7a98f9e7a3)

lots of DXGI errors, and then:
![image](https://github.com/jamesstringerparsec/Easy-GPU-PV/assets/174545517/71d9b9cc-27d9-42a1-9997-3334c999ff4e)

**Comment by kaizendevsio** [comment]
I think latest updates from nvidia and intel disabled the HW encoder inside GPU PV, those fuckers screwed us. It was working beautifully before the update

**Comment by AldoGamez89** [comment]
it's fixed now... I have no idea what I changed in parsec and it worked
