### ISSUE TITLE
How to make parsec not auto-install everytime VM is started?

### ISSUE THREAD

**Issue by TreeOfSelf** [jamesstringerparsec/Easy-GPU-PV#394]
Parsec is trash compared to open-source alternative SunShine/Moonlight. If you insist on having it install with the VM, at least don't have it so it auto installs itself every time the VM is booted.

**Comment by mitchellurgero** [comment]
> Parsec is trash compared to open-source alternative SunShine/Moonlight. If you insist on having it install with the VM, at least don't have it so it auto installs itself every time the VM is booted.

This is a Parsec dev that made this repo, so it makes sense. That said - it's a scheduled task I believe. If you disable it there it should stop autoinstalling.

**Comment by TreeOfSelf** [comment]
Thanks - It seems deleting the  tasks does not work, it will just re-add them. Disabling them does work.

**Comment by TreeOfSelf** [comment]
Nah, actually. Even disabling/deleting the tasks it just re-adds them.

**Comment by SavageTheUnicorn** [comment]
> Nah, actually. Even disabling/deleting the tasks it just re-adds them.
> 
> I just commented out the lines from the CopyFilesToVM.ps1 and that seems to have worked.

Which lines specifically? I'm trying to check myself but I'll probably break the script.

**Comment by TreeOfSelf** [comment]
CopyFilesToVM.ps1

Lines 173-175 I believe are all you need to comment.

**Comment by SavageTheUnicorn** [comment]
I had commented many more than that lol It caused issues after reboot, the Hyper V display adapter would reinstall and reenable every reboot.

**Comment by TreeOfSelf** [comment]
> I had commented many more than that lol It caused issues after reboot, the Hyper V display adapter would reinstall and reenable every reboot.

I could be wrong, but I think the Hyper V display adapter has more to do with the enhanced viewing session of Hyper V than Easy-GPU-PV.  I usually just have the display adapter on to switch to my native resolution, and then disable it after.

**Comment by SavageTheUnicorn** [comment]
> > I had commented many more than that lol It caused issues after reboot, the Hyper V display adapter would reinstall and reenable every reboot.
> 
> I could be wrong, but I think the Hyper V display adapter has more to do with the enhanced viewing session of Hyper V than Easy-GPU-PV. I usually just have the display adapter on to switch to my native resolution, and then disable it after.

Honestly, I'm unsure about this too because for one I have enhanced viewing session entirely disabled, and two I always get stuck back to the Hyper V display adapter default res and refresh rate and I cannot change the refresh rate at all since the ParsecVDD never makes a virtual monitor after the reboot.

**Comment by TreeOfSelf** [comment]
![image](https://github.com/user-attachments/assets/30bfdab9-1f4b-4b96-ab50-041f3a49ad0e)
This is what mine looks like, if I disable the Hyper-V Video, then I can't change resolution. I actually just realized I also have enhanced viewing disabled.

**Comment by SavageTheUnicorn** [comment]
Yeah mine is similar but the monitor shown in display settings when right clicking the desktop reverts to the HyperVMonitor upon reboots and I can't get the ParsecVDA to activate again afterwards

**Comment by SavageTheUnicorn** [comment]
I was missing "host_virtual_monitors = 1
host_privacy_mode = 1" from my config.txt in the guest machine! Rebooted and fixed.
