### ISSUE TITLE
Incapable of Updating Drivers

### ISSUE THREAD

**Issue by UnstructuredFF** [jamesstringerparsec/Easy-GPU-PV#399]
**I had wanted to update my Drivers for my Virtual Machine as I was a few weeks behind on Driver Updates**

**I went ahead & shutdown my VM**

**Updated my Drivers via the Nvidia App**

**Restarted my System**

**Ran the Update-VMGpuPartitionDriver.ps1 in an Administrator: Windows Powershell ISE**

**& yet I have run into this very issue here**

**I would VERY MUCH Appreciate some understanding here as to what I've done wrong.**

![image_2024-08-20_055936464](https://github.com/user-attachments/assets/6f99edda-f2fd-4b09-9d2e-dd29603cc7cb)

**Comment by timminator** [comment]
You're calling the script without any parameters. You changed the parameters in the comment section above the code, not in the actual script.
You can also call the script from a powershell command window after changing the path to the location of the file, without modifying the script itself:

`.\Update-VMGpuPartitionDriver.ps1 -VMName "YourVMName" -GPUName "YourGPUName"`
