### ISSUE TITLE
GPU doesn't show up on taskmanager but does show up on device manager

### ISSUE THREAD

**Issue by amlan111** [jamesstringerparsec/Easy-GPU-PV#409]
I am using Nvidia GeForce RTX 4060. It doesn't show up regardless of whether I use hyper v connect or parsec,  The only way to get it to show up is to add it using this script 
[(De)attach.txt](https://github.com/user-attachments/files/17472822/De.attach.txt)
while the GPU is on. It stops showing up once the VM is restarted, after which I have to redo it again for it to show up in taskmanager. Even then, if I use the game bar it says I'm using 0% GPU and 0% VRAM. How can I be sure that the GPU is being used at all?  I'm using the latest drivers and I have updated them to the VM about a dozen times.

**Comment by Mau8283** [comment]
With the new version of Windows 11 24h2 it does appear in the task manager.

**Comment by amlan111** [comment]
> With the new version of Windows 11 24h2 it does appear in the task manager.

unfortunately not available for me :/

**Comment by malikvogt** [comment]
> > > > With the new version of Windows 11 24h2 it does appear in the task manager.
> > > 
> > > 
> > > unfortunately not available for me :/
> > 
> > 
> > What version of Windows do you have installed on your PC and which one do you have on your virtual machine? I have installed Windows 11 Pro 24h2 on both and it has worked for me, check that the hyper-v display adapter is enabled in the device manager.
> 
> 23H2 on Host and 24H2 on VM. I checked for updates on host but there doesn't seem to be new ones available.

I had the same problem today. Just run the Windows11InstallationAssistant and the 24H2 version will be installed over your old version.

**Comment by amlan111** [comment]
> > > > > With the new version of Windows 11 24h2 it does appear in the task manager.
> > > > 
> > > > 
> > > > unfortunately not available for me :/
> > > 
> > > 
> > > What version of Windows do you have installed on your PC and which one do you have on your virtual machine? I have installed Windows 11 Pro 24h2 on both and it has worked for me, check that the hyper-v display adapter is enabled in the device manager.
> > 
> > 
> > 23H2 on Host and 24H2 on VM. I checked for updates on host but there doesn't seem to be new ones available.
> 
> I had the same problem today. Just run the Windows11InstallationAssistant and the 24H2 version will be installed over your old version.

Btw if you click win+G and switch to the performance tab, does it show any GPU/VRAM usage?

**Comment by malikvogt** [comment]
> Btw if you click win+G and switch to the performance tab, does it show any GPU/VRAM usage?

Maybe you can try to install the Media Feature Pack. This also helped me to run some games.
It was mentioned here: https://github.com/jamesstringerparsec/Easy-GPU-PV/issues/405

**Comment by timminator** [comment]
This is actually the expected behaviour until Windows Version 23H2 and not an issue. The GPU does not show up inside the Task manager.
Only Windows 24H2 with WDDM version 3.2 introduced work graphs that can be seen inside Task Manager.
To verify that your VM has GPU access just open the Device Manager inside your VM and look under display adapters. If your GPU is showing up there without an exclamation mark it worked correctly. There is no need to run any other script.
You can also install the Heaven Benchmark for example inside your VM, run it and check the GPU utilization in Task Manager on your host. It should be increased, when the Heaven Benchmark is running. Then you can see that its working.

**Comment by amlan111** [comment]
> This is actually the expected behaviour until Windows Version 23H2 and not an issue. The GPU does not show up inside the Task manager. Only Windows 24H2 with WDDM version 3.2 introduced work graphs that can be seen inside Task Manager. To verify that your VM has GPU access just open the Device Manager inside your VM and look under display adapters. If your GPU is showing up there without an exclamation mark it worked correctly. There is no need to run any other script. You can also install the Heaven Benchmark for example inside your VM, run it and check the GPU utilization in Task Manager on your host. It should be increased, when the Heaven Benchmark is running. Then you can see that its working.

I just tested that and it went exactly as you said it would. Oh my god thank you so much, you are a godsend. I can't believe I've been freaking out over GPU partitioning for over a week when it's been working as intended all along...
