### ISSUE TITLE
Driver version mismatch between host and guest

### ISSUE THREAD

**Issue by Gravlok** [jamesstringerparsec/Easy-GPU-PV#55]
I've followed the the steps to install the VM with a success. The machine works and can connect to it via Parsec via Internet. The problem is that it cannot run any games on it. Tried 2 of them

- Farming Simulator 22 - I can access main menu but when trying to start the game it CTDs and leaves this entry in Event Log
![event](https://user-images.githubusercontent.com/14020185/149045855-10d2f939-ebb0-4d72-b332-a38324d86685.png)
- Don't Starve Together - just doesn't start whatsoever. Doesn't leave error logs or anything

I've noticed that driver version in guest machine doesn't match the driver version in host machine.

Host (W10 21H2 Education)
![host](https://user-images.githubusercontent.com/14020185/149046214-8a000ddd-7b47-4d3d-b230-2d577e04a646.png)

Guest (W10 21H2 Pro N)
![guest](https://user-images.githubusercontent.com/14020185/149046229-44c5938c-03bd-43d2-b2af-f0a37999660a.png)

I've used DDU to completely remove GPU drivers and did a fresh install (as of writing this current version is 22.1.1). After that used the `Update-VMGpuPartitionDriver.ps1` to update the drivers on guest. Nothing changed. Is the driver mismatch an issue here?

Host specs:
CPU: AMD Ryzen 5 3600 (2c/4t allocated to VM)
GPU: AMD Radeon RX 5700 XT (50% resources allocated to VM)
RAM: 32GB 3200MHz (8GB allocated to VM)

Attaching mentioned Windows Event Log for those interested:
[event.zip](https://github.com/jamesstringerparsec/Easy-GPU-PV/files/7850880/event.zip)

EDIT:
Checked another game CS:GO - same results like with Farming Simulator 22. Can enter main menu, crashes when trying to go into game. No event produced.

**Comment by jamesstringerparsec** [comment]
The VM is running the correct drivers.  You will not see native AMD drivers on the VM.
