### ISSUE TITLE
Fallout 76 host tanks encoding for the Parsec VM

### ISSUE THREAD

**Issue by HalfF0x** [jamesstringerparsec/Easy-GPU-PV#60]
Unsure if this is a problem with the vm/parsec or Bethesda's crappy game, but nonetheless an issue all the same.

Spec as follows.

i5-10600k with 4 cores dedicated to the VM
RTX 3060ti founders
16GB DDR4 3200MHz with 8GB dedicated to the VM.

UAC is off altogether in the VM to avoid the chance of this causing issues.

Fallout 76 when launched begins to start, get a black screen as if it was loading then the game closes altogether, no longer a process in task manager. 
I've been through the troubleshooting on the Bethesda side of things. Ensuring run as admin, re-installing the game. New VM and then re-installing the game from scratch and no dice. 

I've had multiple other games running fine:
Dark souls 3
The Witcher 3
Deep Rock Galactic
So I know the gpu pass through works. 

Any thoughts/ideas?

Thanks

Edit: I'm installing it through the xbox/Microsoft store now as I have gamepass to see if that resolves the issue. Will keep you posted.

**Comment by jamesstringerparsec** [comment]
Is your host running Win10 or Win11?

**Comment by HalfF0x** [comment]
Win 11 for both the host and the VM

**Comment by jamesstringerparsec** [comment]
You could try a Win11 Insider Preview Dev channel ISO perhaps on a VM.  It may increase compatibility but I'm not completely sure if it will solve your issue with Fallout.

**Comment by HalfF0x** [comment]
> You could try a Win11 Insider Preview Dev channel ISO perhaps on a VM. It may increase compatibility but I'm not completely sure if it will solve your issue with Fallout.

Its worth a punt. I'll give a try if the windows store version doesn't work. 👍

**Comment by HalfF0x** [comment]
> You could try a Win11 Insider Preview Dev channel ISO perhaps on a VM. It may increase compatibility but I'm not completely sure if it will solve your issue with Fallout.

The windows version will boot in the virtual machine, I am presented with another issue now though.

I run the Windows store version on the VM, and it runs perfectly. Starting the Bethesda.net version on the host then causes encode to jump up to around 110 - 150ms and bounces around between those two figures. Tanking performance on the stream.

In task manager, GPU Encode before booting the host game is between 6 - 12%. As soon as the host game starts this jumps up to 100% and is pegged there.

Is there a way to offload encoding to the cpu in Parsec to see if this would circumvent the issue?

**Comment by jamesstringerparsec** [comment]
Does this happen if you install the same version on your hyper-v host and
connect to it with parsec? Not sure if you have a secondary laptop or
android phone you can use to connect to it and observe the encode time.

**Comment by HalfF0x** [comment]
So I think there must be issue with the Bethesda.net version of the game and this particular solution.

Running the xbox store version in the vm and connecting to that vm via parsec is fine. If I run another game on the host, dark souls 3 for example. Both fallout 76 on the vm and connected via parsec and the host game run perfectly fine. Encoding has no issue and the experience is smooth for the host and the remote device. 

Now if I run the xbox app of fo76 in the vm, it runs perfectly well until I start the Bethesda.net version of fo76 on the host, at which point it it tanks the gpu encode. This is before there is even a display from the host fo76 but the executable has began to run and can be seen in host task manager. Either that or its the drm used in the Bethesda.net app itself?

Which leads me to believe that there is some issue with the Bethesda.bet version of fo76, as this refuses to start up at all within a VM.

**Comment by HalfF0x** [comment]
So running both versions through the xbox store on gamepass has rectificied the issue. 

Definitely an issue with the Bethesda.net version.

**Comment by jamesstringerparsec** [comment]
ok so it works OK now on gamepass without crazy high latency?

**Comment by HalfF0x** [comment]
Yes, it works perfectly with the game pass versions!!
