### ISSUE TITLE
The script is great! But was intended for new vms...

### ISSUE THREAD

**Issue by codygamer666** [jamesstringerparsec/Easy-GPU-PV#65]
The script is great and very easy to use (before was a nightmare, in particular finding the right drivers in sys32), but as stated above it's designed to create a new vm. I think there are a lot of devs or IT guys like myself that already have running production/testing vms and don't want to waste a gpu for each vm using dda. 

I tested your scripts against a premade vm and i found out that a simple new script combined with "Update-VMGpuPartitionDriver.ps1" can successfully add gpu-p to an existing vm with zero effort.

The steps that i followed:
1. Created the script for adding gpu-p:
add-gpu-p.ps1
```
$vm = "TESTVM"
Remove-VMGpuPartitionAdapter -VMName $vm
Add-VMGpuPartitionAdapter -VMName $vm
Set-VMGpuPartitionAdapter -VMName $vm -MinPartitionVRAM 1
Set-VMGpuPartitionAdapter -VMName $vm -MaxPartitionVRAM 11
Set-VMGpuPartitionAdapter -VMName $vm -OptimalPartitionVRAM 10
Set-VMGpuPartitionAdapter -VMName $vm -MinPartitionEncode 1
Set-VMGpuPartitionAdapter -VMName $vm -MaxPartitionEncode 11
Set-VMGpuPartitionAdapter -VMName $vm -OptimalPartitionEncode 10
Set-VMGpuPartitionAdapter -VMName $vm -MinPartitionDecode 1
Set-VMGpuPartitionAdapter -VMName $vm -MaxPartitionDecode 11
Set-VMGpuPartitionAdapter -VMName $vm -OptimalPartitionDecode 10
Set-VMGpuPartitionAdapter -VMName $vm -MinPartitionCompute 1
Set-VMGpuPartitionAdapter -VMName $vm -MaxPartitionCompute 11
Set-VMGpuPartitionAdapter -VMName $vm -OptimalPartitionCompute 10
Set-VM -GuestControlledCacheTypes $true -VMName $vm
Set-VM -LowMemoryMappedIoSpace 1Gb -VMName $vm
Set-VM -HighMemoryMappedIoSpace 32GB -VMName $vm
```
2. Run the script using powershell 

3. Modify "Update-VMGpuPartitionDriver.ps1" parameters for the vm (vm name, gpu name "AUTO" or for a specific gpu "NVIDIA GeForce RTX 2060")
Full example:
```
Param (
[string]$VMName = "TESTVM",
[string]$GPUName = "AUTO",
[string]$Hostname = $ENV:Computername
)
```
4. Run the modified script and then start the vm
5. After the vm starts disable hyper-v monitor in device manager and start using the gpu

BTW I used a Lenovo Legion 5 for testing with a Ryzen 4800h and rtx 2060, the radeon was fully working except for parsec and the rtx was working 100% using parsec. This proves that laptops and gpu-p work in some cases, if you are lucky.

I hope this helps in some way

**Comment by Doge5678** [comment]
I did the same it worked but what do you mean by hyper v monitor I couldn't find something like that

**Comment by codygamer666** [comment]
Sorry i mistyped, it's called "Microsoft Hyper-V Video".
In my case (italian) the name is a bit reversed, but similar:

![GPU-P1](https://user-images.githubusercontent.com/96527590/149303807-c8636194-8b33-4252-8e31-488ad8c89735.JPG)

BTW for all gpu-p users: if the monitor resolution is stuck just use CRU and create a custom resolution:
1. The resolution is locked
![gpu-p2](https://user-images.githubusercontent.com/96527590/149305643-c4640e08-56b2-4b15-8cd1-f9b04fc00e1f.JPG)

2. Download and open CRU, then fill all the blank parameters with your desired resolution 
![gpu-p3](https://user-images.githubusercontent.com/96527590/149305824-cadb61ca-2171-4465-ab75-05ac35a0a421.JPG)

3. Close CRU and run restart.exe or restart64.exe
![gpu-p4](https://user-images.githubusercontent.com/96527590/149305973-a772c1bd-0efb-45a4-bbaa-11beb7999ec6.JPG)

4. Enjoy the resolution you chose

I know that cru is out of topic, but man this script is just underutilized. It's not for just creating a new vm, it has a large set of functions that are very useful if fully advertised in the main page.

I hope @jamesstringerparsec takes this flaming ball and adds this findings in the main page after testing

**Comment by jamesstringerparsec** [comment]
Hi, I appreciate your enthusiasm, but telling users to do this is not helpful. This information is causing users to setup their VM incorrectly. There is a Parsec Virtual Display Driver installed which will allow the user to steam any resolution they want, and at a varying number of refresh rates. This monitor is created on connection and also disables other monitors at the same time. If this is not working I want to fix it, rather than tell people to do a bunch of random stuff.

**Comment by jamesstringerparsec** [comment]
In addition, your Set-VMGpuPartitionAdapter values quoted on your script will result in very low performance on the VM.  Once again, thanks for your enthusiasm but it's causing more problems than it's solving.

**Comment by codygamer666** [comment]
> In addition, your Set-VMGpuPartitionAdapter values quoted on your script will result in very low performance on the VM. Once again, thanks for your enthusiasm but it's causing more problems than it's solving.

Do you think something like this is good?:
```
Param (
[string]$VMName = "10-SUEZ",
[string]$GPUName = "AUTO",
[string]$Hostname = $ENV:Computername,
[decimal]$GPUResourceAllocationPercentage = 100
)

Function Add-VMGpuPartitionAdapterFiles {
param(
[string]$hostname = $ENV:COMPUTERNAME,
[string]$DriveLetter,
[string]$GPUName
)

If (!($DriveLetter -like "*:*")) {
    $DriveLetter = $Driveletter + ":"
    }

If ($GPUName -eq "AUTO") {
    $PartitionableGPUList = Get-WmiObject -Class "Msvm_PartitionableGpu" -ComputerName $env:COMPUTERNAME -Namespace "ROOT\virtualization\v2"
    $DevicePathName = $PartitionableGPUList.Name | Select-Object -First 1
    $GPU = Get-PnpDevice | Where-Object {($_.DeviceID -like "*$($DevicePathName.Substring(8,16))*") -and ($_.Status -eq "OK")} | Select-Object -First 1
    $GPUName = $GPU.Friendlyname
    $GPUServiceName = $GPU.Service 
    }
Else {
    $GPU = Get-PnpDevice | Where-Object {($_.Name -eq "$GPUName") -and ($_.Status -eq "OK")} | Select-Object -First 1
    $GPUServiceName = $GPU.Service
    }
# Get Third Party drivers used, that are not provided by Microsoft and presumably included in the OS

Write-Host "INFO   : Finding and copying driver files for $GPUName to VM. This could take a while..."

$Drivers = Get-WmiObject Win32_PNPSignedDriver | where {$_.DeviceName -eq "$GPUName"}

New-Item -ItemType Directory -Path "$DriveLetter\windows\system32\HostDriverStore" -Force | Out-Null

#copy directory associated with sys file 
$servicePath = (Get-WmiObject Win32_SystemDriver | Where-Object {$_.Name -eq "$GPUServiceName"}).Pathname
                $ServiceDriverDir = $servicepath.split('\')[0..5] -join('\')
                $ServicedriverDest = ("$driveletter" + "\" + $($servicepath.split('\')[1..5] -join('\'))).Replace("DriverStore","HostDriverStore")
                if (!(Test-Path $ServicedriverDest)) {
                Copy-item -path "$ServiceDriverDir" -Destination "$ServicedriverDest" -Recurse
                }

# Initialize the list of detected driver packages as an array
$DriverFolders = @()
foreach ($d in $drivers) {

    $DriverFiles = @()
    $ModifiedDeviceID = $d.DeviceID -replace "\\", "\\"
    $Antecedent = "\\" + $hostname + "\ROOT\cimv2:Win32_PNPSignedDriver.DeviceID=""$ModifiedDeviceID"""
    $DriverFiles += Get-WmiObject Win32_PNPSignedDriverCIMDataFile | where {$_.Antecedent -eq $Antecedent}
    $DriverName = $d.DeviceName
    $DriverID = $d.DeviceID
    if ($DriverName -like "NVIDIA*") {
        New-Item -ItemType Directory -Path "$driveletter\Windows\System32\drivers\Nvidia Corporation\" -Force | Out-Null
        }
    foreach ($i in $DriverFiles) {
            $path = $i.Dependent.Split("=")[1] -replace '\\\\', '\'
            $path2 = $path.Substring(1,$path.Length-2)
            $InfItem = Get-Item -Path $path2
            $Version = $InfItem.VersionInfo.FileVersion
            If ($path2 -like "c:\windows\system32\driverstore\*") {
                $DriverDir = $path2.split('\')[0..5] -join('\')
                $driverDest = ("$driveletter" + "\" + $($path2.split('\')[1..5] -join('\'))).Replace("driverstore","HostDriverStore")
                if (!(Test-Path $driverDest)) {
                Copy-item -path "$DriverDir" -Destination "$driverDest" -Recurse
                }
            }
            Else {
                $ParseDestination = $path2.Replace("c:", "$driveletter")
                $Destination = $ParseDestination.Substring(0, $ParseDestination.LastIndexOf('\'))
                if (!$(Test-Path -Path $Destination)) {
                    New-Item -ItemType Directory -Path $Destination -Force | Out-Null
                    }
                Copy-Item $path2 -Destination $Destination -Force
                
            }

    }
    }

}

$VM = Get-VM -VMName $VMName
$VHD = Get-VHD -VMId $VM.VMId

If ($VM.state -eq "Running") {
    [bool]$state_was_running = $true
    }

if ($VM.state -ne "Off"){
    "Attemping to shutdown VM..."
    Stop-VM -Name $VMName -Force
    } 

While ($VM.State -ne "Off") {
    Start-Sleep -s 3
    "Waiting for VM to shutdown - make sure there are no unsaved documents..."
    }

"Mounting Drive..."
$DriveLetter = (Mount-VHD -Path $VHD.Path -PassThru | Get-Disk | Get-Partition | Get-Volume | Where-Object {$_.DriveLetter} | ForEach-Object DriveLetter)

"Copying GPU Files - this could take a while..."
Add-VMGPUPartitionAdapterFiles -hostname $Hostname -DriveLetter $DriveLetter -GPUName $GPUName

"Dismounting Drive..."
Dismount-VHD -Path $VHD.Path

function Assign-VMGPUPartitionAdapter 
{  
    $PartitionableGPUList = Get-WmiObject -Class "Msvm_PartitionableGpu" -ComputerName $env:COMPUTERNAME -Namespace "ROOT\virtualization\v2" 
    if ($GPUName -eq "AUTO") {
        $DevicePathName = $PartitionableGPUList.Name[0]
        Add-VMGpuPartitionAdapter -VMName $VMName
        }
    else {
        $DeviceID = ((Get-WmiObject Win32_PNPSignedDriver | where {($_.Devicename -eq "$GPUNAME")}).hardwareid).split('\')[1]
        $DevicePathName = ($PartitionableGPUList | Where-Object name -like "*$deviceid*").Name
        Add-VMGpuPartitionAdapter -VMName $VMName -InstancePath $DevicePathName
        }

    [float]$devider = [math]::round($(100 / $GPUResourceAllocationPercentage),2)

    Set-VMGpuPartitionAdapter -VMName $VMName -MinPartitionVRAM ([math]::round($(1000000000 / $devider))) -MaxPartitionVRAM ([math]::round($(1000000000 / $devider))) -OptimalPartitionVRAM ([math]::round($(1000000000 / $devider)))
    Set-VMGPUPartitionAdapter -VMName $VMName -MinPartitionEncode ([math]::round($(18446744073709551615 / $devider))) -MaxPartitionEncode ([math]::round($(18446744073709551615 / $devider))) -OptimalPartitionEncode ([math]::round($(18446744073709551615 / $devider)))
    Set-VMGpuPartitionAdapter -VMName $VMName -MinPartitionDecode ([math]::round($(1000000000 / $devider))) -MaxPartitionDecode ([math]::round($(1000000000 / $devider))) -OptimalPartitionDecode ([math]::round($(1000000000 / $devider)))
    Set-VMGpuPartitionAdapter -VMName $VMName -MinPartitionCompute ([math]::round($(1000000000 / $devider))) -MaxPartitionCompute ([math]::round($(1000000000 / $devider))) -OptimalPartitionCompute ([math]::round($(1000000000 / $devider)))

}

"Assigning GPU-P Adapter"
Assign-VMGPUPartitionAdapter

If ($state_was_running){
    "Previous State was running so starting VM..."
    Start-VM $VMName
    }

"Done..."
```
I merged your "Update-VMGpuPartitionDriver.ps1" and "Add-VMGpuPartitionAdapterFiles.psm1" and added the gpu-p code from "CopyFilesToVM.ps1". Not perfect, but now the performance is good

**Comment by jamesstringerparsec** [comment]
Yea that's the idea, I will be making an official method to modify gpu assignment or add an assignment to an existing VM in the next week or so.

**Comment by codygamer666** [comment]
> 



> > In addition, your Set-VMGpuPartitionAdapter values quoted on your script will result in very low performance on the VM. Once again, thanks for your enthusiasm but it's causing more problems than it's solving.
> 
> Do you think something like this is good?:
> 
> ```
> Param (
> [string]$VMName = "TEST",
> [string]$GPUName = "AUTO",
> [string]$Hostname = $ENV:Computername,
> [decimal]$GPUResourceAllocationPercentage = 100
> )
> 
> Function Add-VMGpuPartitionAdapterFiles {
> param(
> [string]$hostname = $ENV:COMPUTERNAME,
> [string]$DriveLetter,
> [string]$GPUName
> )
> 
> If (!($DriveLetter -like "*:*")) {
>     $DriveLetter = $Driveletter + ":"
>     }
> 
> If ($GPUName -eq "AUTO") {
>     $PartitionableGPUList = Get-WmiObject -Class "Msvm_PartitionableGpu" -ComputerName $env:COMPUTERNAME -Namespace "ROOT\virtualization\v2"
>     $DevicePathName = $PartitionableGPUList.Name | Select-Object -First 1
>     $GPU = Get-PnpDevice | Where-Object {($_.DeviceID -like "*$($DevicePathName.Substring(8,16))*") -and ($_.Status -eq "OK")} | Select-Object -First 1
>     $GPUName = $GPU.Friendlyname
>     $GPUServiceName = $GPU.Service 
>     }
> Else {
>     $GPU = Get-PnpDevice | Where-Object {($_.Name -eq "$GPUName") -and ($_.Status -eq "OK")} | Select-Object -First 1
>     $GPUServiceName = $GPU.Service
>     }
> # Get Third Party drivers used, that are not provided by Microsoft and presumably included in the OS
> 
> Write-Host "INFO   : Finding and copying driver files for $GPUName to VM. This could take a while..."
> 
> $Drivers = Get-WmiObject Win32_PNPSignedDriver | where {$_.DeviceName -eq "$GPUName"}
> 
> New-Item -ItemType Directory -Path "$DriveLetter\windows\system32\HostDriverStore" -Force | Out-Null
> 
> #copy directory associated with sys file 
> $servicePath = (Get-WmiObject Win32_SystemDriver | Where-Object {$_.Name -eq "$GPUServiceName"}).Pathname
>                 $ServiceDriverDir = $servicepath.split('\')[0..5] -join('\')
>                 $ServicedriverDest = ("$driveletter" + "\" + $($servicepath.split('\')[1..5] -join('\'))).Replace("DriverStore","HostDriverStore")
>                 if (!(Test-Path $ServicedriverDest)) {
>                 Copy-item -path "$ServiceDriverDir" -Destination "$ServicedriverDest" -Recurse
>                 }
> 
> # Initialize the list of detected driver packages as an array
> $DriverFolders = @()
> foreach ($d in $drivers) {
> 
>     $DriverFiles = @()
>     $ModifiedDeviceID = $d.DeviceID -replace "\\", "\\"
>     $Antecedent = "\\" + $hostname + "\ROOT\cimv2:Win32_PNPSignedDriver.DeviceID=""$ModifiedDeviceID"""
>     $DriverFiles += Get-WmiObject Win32_PNPSignedDriverCIMDataFile | where {$_.Antecedent -eq $Antecedent}
>     $DriverName = $d.DeviceName
>     $DriverID = $d.DeviceID
>     if ($DriverName -like "NVIDIA*") {
>         New-Item -ItemType Directory -Path "$driveletter\Windows\System32\drivers\Nvidia Corporation\" -Force | Out-Null
>         }
>     foreach ($i in $DriverFiles) {
>             $path = $i.Dependent.Split("=")[1] -replace '\\\\', '\'
>             $path2 = $path.Substring(1,$path.Length-2)
>             $InfItem = Get-Item -Path $path2
>             $Version = $InfItem.VersionInfo.FileVersion
>             If ($path2 -like "c:\windows\system32\driverstore\*") {
>                 $DriverDir = $path2.split('\')[0..5] -join('\')
>                 $driverDest = ("$driveletter" + "\" + $($path2.split('\')[1..5] -join('\'))).Replace("driverstore","HostDriverStore")
>                 if (!(Test-Path $driverDest)) {
>                 Copy-item -path "$DriverDir" -Destination "$driverDest" -Recurse
>                 }
>             }
>             Else {
>                 $ParseDestination = $path2.Replace("c:", "$driveletter")
>                 $Destination = $ParseDestination.Substring(0, $ParseDestination.LastIndexOf('\'))
>                 if (!$(Test-Path -Path $Destination)) {
>                     New-Item -ItemType Directory -Path $Destination -Force | Out-Null
>                     }
>                 Copy-Item $path2 -Destination $Destination -Force
>                 
>             }
> 
>     }
>     }
> 
> }
> 
> $VM = Get-VM -VMName $VMName
> $VHD = Get-VHD -VMId $VM.VMId
> 
> If ($VM.state -eq "Running") {
>     [bool]$state_was_running = $true
>     }
> 
> if ($VM.state -ne "Off"){
>     "Attemping to shutdown VM..."
>     Stop-VM -Name $VMName -Force
>     } 
> 
> While ($VM.State -ne "Off") {
>     Start-Sleep -s 3
>     "Waiting for VM to shutdown - make sure there are no unsaved documents..."
>     }
> 
> "Mounting Drive..."
> $DriveLetter = (Mount-VHD -Path $VHD.Path -PassThru | Get-Disk | Get-Partition | Get-Volume | Where-Object {$_.DriveLetter} | ForEach-Object DriveLetter)
> 
> "Copying GPU Files - this could take a while..."
> Add-VMGPUPartitionAdapterFiles -hostname $Hostname -DriveLetter $DriveLetter -GPUName $GPUName
> 
> "Dismounting Drive..."
> Dismount-VHD -Path $VHD.Path
> 
> function Assign-VMGPUPartitionAdapter 
> {  
>     $PartitionableGPUList = Get-WmiObject -Class "Msvm_PartitionableGpu" -ComputerName $env:COMPUTERNAME -Namespace "ROOT\virtualization\v2" 
>     if ($GPUName -eq "AUTO") {
>         $DevicePathName = $PartitionableGPUList.Name[0]
>         Add-VMGpuPartitionAdapter -VMName $VMName
>         }
>     else {
>         $DeviceID = ((Get-WmiObject Win32_PNPSignedDriver | where {($_.Devicename -eq "$GPUNAME")}).hardwareid).split('\')[1]
>         $DevicePathName = ($PartitionableGPUList | Where-Object name -like "*$deviceid*").Name
>         Add-VMGpuPartitionAdapter -VMName $VMName -InstancePath $DevicePathName
>         }
> 
>     [float]$devider = [math]::round($(100 / $GPUResourceAllocationPercentage),2)
> 
>     Set-VMGpuPartitionAdapter -VMName $VMName -MinPartitionVRAM ([math]::round($(1000000000 / $devider))) -MaxPartitionVRAM ([math]::round($(1000000000 / $devider))) -OptimalPartitionVRAM ([math]::round($(1000000000 / $devider)))
>     Set-VMGPUPartitionAdapter -VMName $VMName -MinPartitionEncode ([math]::round($(18446744073709551615 / $devider))) -MaxPartitionEncode ([math]::round($(18446744073709551615 / $devider))) -OptimalPartitionEncode ([math]::round($(18446744073709551615 / $devider)))
>     Set-VMGpuPartitionAdapter -VMName $VMName -MinPartitionDecode ([math]::round($(1000000000 / $devider))) -MaxPartitionDecode ([math]::round($(1000000000 / $devider))) -OptimalPartitionDecode ([math]::round($(1000000000 / $devider)))
>     Set-VMGpuPartitionAdapter -VMName $VMName -MinPartitionCompute ([math]::round($(1000000000 / $devider))) -MaxPartitionCompute ([math]::round($(1000000000 / $devider))) -OptimalPartitionCompute ([math]::round($(1000000000 / $devider)))
> 
> }
> 
> "Assigning GPU-P Adapter"
> Assign-VMGPUPartitionAdapter
> 
> If ($state_was_running){
>     "Previous State was running so starting VM..."
>     Start-VM $VMName
>     }
> 
> "Done..."
> ```
> 
> I merged your "Update-VMGpuPartitionDriver.ps1" and "Add-VMGpuPartitionAdapterFiles.psm1" and added the gpu-p code from "CopyFilesToVM.ps1". Not perfect, but now the performance is good
> 
> EDIT: I forgot to remove the old vm name that i used

I will try to update this with a line interactive input for vm name and gpu name, 

> Yea that's the idea, I will be making an official method to modify gpu assignment or add an assignment to an existing VM in the next week or so.

I was thinking, some kind of selection menu? like an option select:
1 For Creating A New VM
2 For Adding GPU-P To A VM
3 For Updating The Drivers

and then a line interactive script to insert the vm name and gpu name.
I will give it a try right now and see if this can work

**Comment by codygamer666** [comment]
Some progress, adjusting the scripts to work well with a menu, second iteration to add a shared vm property file or add line prompt to add vm name and the other stuff. Right now the new vm script is working
![PROGRESS 1](https://user-images.githubusercontent.com/96527590/149357046-8c940432-cca5-4581-bcdf-eea66d87e53d.JPG)

**Comment by codygamer666** [comment]
> Something like this:
> 
> ```
> $VMName = Read-Host -Prompt 'Input your VM name'
> $GPUName = Read-Host -Prompt 'Input the gpu model or type AUTO for automatic installation'
> $Hostname = $ENV:Computername
> ```
> 
> working in the menu right now, i think 1 hr and my fork is complete with a menu and an interactive cli

I'll upload now my menu with user capable input. Give it a try and let me know if it works for someone other than me. I'll be happy to close my fork if the original has something like this...

**Comment by danieliser** [comment]
@jamesstringerparsec this was marked completed, but I don't see anything in the readme or files to handle adding to an existing VM.

That said the current version to create new VM's is not working for me on a nested VM. That is Epyc CPU / Nvidia 3090 GPU, host proxmox -> Windows 11 (host with passthrough GPU) -> Windows 11 VM.

When I create a VM using the readme instructions it won't boot, says my hardware doesn't support nested virtualization.

But if I manually create the VM it boots fine.

And if I use the proposed methods above I do in fact end up with a 3090 exposed in the nested VM and it boots fine, but it obviously doesn't include the parsec stuff at all and I haven't tested if the 3090 properly gets used inside the VM just yet.

What is the proposed way of implementing this on an existing VM so I can validate if the `nested virtualization` issue from the main script is an actual issue with nesting inside proxmox, or something else.

**Comment by danieliser** [comment]
@jamesstringerparsec update, and gonna open new ticket for this officially, but for reference, the issue was with the following lines:

https://github.com/jamesstringerparsec/Easy-GPU-PV/blob/main/CopyFilesToVM.ps1#L4377-L4381

It seems on my nested->nested setup, proxmox is set to use `host`  CPU type, but must not be passing all the flags required to prevent that check from failing. And when it fails it enables the virtualized flag, this seems to be what prevents it from booting.

**Comment by e-t-l** [comment]
> Yea that's the idea, I will be making an official method to modify gpu assignment or add an assignment to an existing VM in the next week or so.

What's the status on this? Do the scripts in the official repo handle existing VMs, or should I use the code in this issue?
