### ISSUE TITLE
Privacy mode has encountered a display error and is inactive.

### ISSUE THREAD

**Issue by Quatern1on** [jamesstringerparsec/Easy-GPU-PV#66]
I created a new VM, connected via viewport signed in into parsec, then disconnected from viewport and connected via parsec. Connection is working but I am getting this error: "Privacy mode has encountered a display error and is inactive. Try reconnecting, otherwise contact us if this message persists." I tried to uninstall parsec and VDD, reboot and wait for it to install itself again (as suggested in other issue) but it didn't work:
![image](https://user-images.githubusercontent.com/63079104/149263257-012084d8-1e02-4c48-bc12-17d8da48d4f7.png)
I am also unable to change resoultion:
![image](https://user-images.githubusercontent.com/63079104/149264025-c3ec53b0-4ab2-4b15-b0c7-97f66c603d96.png)
Device manager:
![image](https://user-images.githubusercontent.com/63079104/149264266-95c80c83-665d-42aa-bdf4-5b0d1ef5abcb.png)
 C:\ProgramData\Parsec\config.txt:
![image](https://user-images.githubusercontent.com/63079104/149263879-34437c91-650a-45a2-b1d7-d499aa4cbe8a.png)
My configuration:
Ryzen 5 2600
NVidia GTX 1660

**Comment by jamesstringerparsec** [comment]
Is this a laptop or a desktop?

**Comment by Noah-1337** [comment]
I have the same issue as it seems, but i sadly didn't fix itself

**Comment by Quatern1on** [comment]
Have you tried restarting your whole PC? I know this is stupid suggestion, but it seems like that was what helped me then.
