### ISSUE TITLE
Correct way to uninstall Easy-GPU-PV

### ISSUE THREAD

**Issue by KGeetings** [jamesstringerparsec/Easy-GPU-PV#70]
I have found another solution that I believe works better for my use case and was hoping to uninstall Easy-GPU-PV. There does not seem to be clear documentation on how to go about uninstalling it correctly. And while I did remove all the files related to Easy-GPU-PV that I had downloaded, it does seem to still be adding Ethernet drivers that show up in my task manager that I can't seem to fully remove. I am also unable to delete the Windows 10 ISO file I downloaded as I get an error saying "the file is open in System."

**Comment by jamesstringerparsec** [comment]
Easy-GPU-PV doesn't install to your system, but you can shutdown your Hyper-V VM by searching Hyper-V Manager on your computer, and if you want to uninstall Hyper-V entirely you can visit this page to show you how.  https://www.nakivo.com/blog/uninstalling-or-disabling-hyper-v-in-windows-10/

**Comment by KGeetings** [comment]
Ah, that must be what I've been missing. Thank you.

**Comment by DannyZ77** [comment]
So to clarify if I just delete/turn off the vm, all the gpu resources are freed?, I know this is just a script that runs a bunch of PowerShell commands and installs parsec while partitioning the gpu, what my doubt is do I need to run to those commands again to revert or just deleting the vm is fine?
