### ISSUE TITLE
Failed to Format system volume and windows volume resulting in the script thinking that it failed to create the VHDX

### ISSUE THREAD

**Issue by HolyHobo-chan** [jamesstringerparsec/Easy-GPU-PV#72]
[Convert-WindowsImageTranscript.txt](https://github.com/jamesstringerparsec/Easy-GPU-PV/files/7865451/Convert-WindowsImageTranscript.txt)
Here is the log that was given to me by the script. As the title says, it successfully creates and mounts the VHDX, it just fails to format the VHDX. It looks like it might be an invalid parameter?

**Comment by jamesstringerparsec** [comment]
Please post your comment here https://github.com/jamesstringerparsec/Easy-GPU-PV/issues/45 , this issue is a duplicate
