### ISSUE TITLE
Locked Resolution After

### ISSUE THREAD

**Issue by GeorgeToy** [jamesstringerparsec/Easy-GPU-PV#73]
I've rerun the script multiple times and after a restart the resolution locks to 1024x768 which is not my problem really, it's that when I run Parsec it says there's a problem with the display driver and is still on 1024x768 . Any help is appreciated

**Comment by jamesstringerparsec** [comment]
Go to C:\programdata\parsec\config.txt and copy what's in there and paste
it here

**Comment by GeorgeToy** [comment]
Nvm I managed to fix by running it and making it save on my ssd idk maybe it was a slow drive

**Comment by GeorgeToy** [comment]
# All configuration settings must appear on a new line.
# All whitespace, besides the newline character '\n', is ignored.
# All settings passed via the command line take precedence.
# The configuration file will be overwritten by Parsec when changing settings,
#   so if you edit this file while Parsec is running, make sure to save this file
#   and restart Parsec immediately so your changes are preserved.

# Example:
# encoder_bitrate = 10

app_run_level = 1
host_virtual_monitors = 1
host_privacy_mode = 1
