### ISSUE TITLE
Most games have crashed on VM.

### ISSUE THREAD

**Issue by WorkMC** [jamesstringerparsec/Easy-GPU-PV#76]
#### I used a translator.

---
```
Host :
OS - Windows 10 Enterprise 21H2 x64
CPU - Intel Core I7-9700KF
RAM - 16GB (Overclocked)
GPU - RTX 2060 SUPER ( Driver : 497.29[Latest] )
```

```
Guest :
OS - Windows 11 Pro 21H2 x64
CPU Cores - 4 Core
RAM - 8GB
GPUResourceAllocationPercentage - 50
```

```
CopyFilesToVM.ps1

$params = @{
    VMName = "GamePC0001"
    SourcePath = "D:\Captures\ko_windows_11_21H2_MSDN.iso"
    Edition    = 6
    VhdFormat  = "VHDX"
    DiskLayout = "UEFI"
    SizeBytes  = 40GB
    MemoryAmount = 8GB
    CPUCores = 4
    NetworkSwitch = "Default Switch"
    VHDPath = "C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\"
    UnattendPath = "$PSScriptRoot"+"\autounattend.xml"
    GPUName = "AUTO"
    GPUResourceAllocationPercentage = 50
    Team_ID = ""
    Key = ""
    Username = "GamePC"
    Password = "@@@@"
    Autologon = "true"
}
```
---

#### Crash dump (img) :
![c](https://user-images.githubusercontent.com/62065753/149451442-728284d1-c100-42d2-be34-af95124b5a87.PNG)
![c2](https://user-images.githubusercontent.com/62065753/149458624-3bdeebc7-3d39-473e-b177-462a229141f9.PNG)

#### Crash gif :
![crash](https://user-images.githubusercontent.com/62065753/149453124-6b37cb2a-b8cf-41ed-83ed-d17f069cb462.gif)

**Comment by jamesstringerparsec** [comment]
The best thing to do is likely upgrade your host computer to windows 11 and create a new VM once you have upgraded. There is better compatibility with games but I can't guarantee anything
