### ISSUE TITLE
is it possible to get Vulkan working?

### ISSUE THREAD

**Issue by prism2001** [jamesstringerparsec/Easy-GPU-PV#78]
so anything using DirectX works, but any games/emulators that use Vulkan or OpenGL don't work. is there something I can do to enable vulkan support or am I only limited to DirectX?

**Comment by jamesstringerparsec** [comment]
See the readme regarding OpenGL and Vulkan support.

**Comment by jacky400** [comment]
OpenGL should work and I tested it with yuzu (Switch Emulator). However , vulkan onlys work in enhanced session mode

**Comment by grrminator** [comment]
https://github.com/grrminator/Easy-GPU-PV

Try this. I dont mean to plug. But Parsec's Virtual Display adapter fucks everything up. This will work if you follow ALL of the instruction steps.
