### ISSUE TITLE
is there any chance for a 2 or more display setup?

### ISSUE THREAD

**Issue by Kante88** [jamesstringerparsec/Easy-GPU-PV#81]
i would like to have 2 monitors on my client pc to work in Autodesk Revit and so on. Revit works fine.

**Comment by Gravlok** [comment]
> "Add Screens" is an option available for Teams and Warp customers. It opens up additional windows to view up to 3 displays from the same host computer at once.

First paragraph from Parsec _Getting Started_ support page. Although you could try and modify line in C:\ProgramData\Parsec\config.txt `host_virtual_monitors = 1` and change it to 2.
