### ISSUE TITLE
ERROR: This ISO is invalid .

### ISSUE THREAD

**Issue by Albusaidi30** [jamesstringerparsec/Easy-GPU-PV#83]
Hello

i have change the secript as steps , but when i change the ISO path shows me the error:

" ERROR: This ISO is invalid, please check readme for ISO downloading instructions. "

how to fix this ?? should i make some thing to ISO

this is the changes i have mede:

$params = @{
    VMName = "GPU"
    SourcePath = "C:\Users\Albus3idi\Desktop\iso\Win10.iso"
    Edition    = 6
    VhdFormat  = "VHDX"
    DiskLayout = "UEFI"
    SizeBytes  = 40GB
    MemoryAmount = 4GB
    CPUCores = 4
    NetworkSwitch = "Default Switch"
    VHDPath = "C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\"
    UnattendPath = "$PSScriptRoot"+"\autounattend.xml"
    GPUName = "AUTO"
    GPUResourceAllocationPercentage = 50
    Team_ID = ""
    Key = ""
    Username = "Jozeiph"
    Password = "steam"
    Autologon = "true"
}

**Comment by jamesstringerparsec** [comment]
Please read the readme as the error suggests...
