### ISSUE TITLE
Always says: Failed to create VHDX

### ISSUE THREAD

**Issue by matei9** [jamesstringerparsec/Easy-GPU-PV#84]
When i run the copyfilestovm script, it always fails, and says, faied to create VHDX, stopping script (i'm running the script in powershell ISE.) Here is the log file.

[convert log.txt](https://github.com/jamesstringerparsec/Easy-GPU-PV/files/7874456/convert.log.txt)

**Comment by jamesstringerparsec** [comment]
Follow this guide to make sure auto mount is enabled and try again https://www.tenforums.com/tutorials/117336-enable-disable-automount-new-disks-drives-windows.html

**Comment by matei9** [comment]
Thank you so much!!!!!! It worked!
