### ISSUE TITLE
GPU doesn't seem to be used for 3d in a Windows 11 guest

### ISSUE THREAD

**Issue by slaykovsky** [jamesstringerparsec/Easy-GPU-PV#87]
Hi there,
Hope you're doing well.

First of all, thank you for sharing these scripts ;)

# Problem
I got a problem with 3D in a Windows 11 guest vm. It seems like the GPU isn't being used for 3d at all.
Furmark doesn't even start, Unigine Heaven gives me around 10 fps. Most of the games don't work too, and when they do there's around 10fps.

## Guest Device manager:
![image](https://user-images.githubusercontent.com/1875374/149632037-9a72f9af-784e-4d7a-a65a-01a5f5a5c57b.png)

## Guest dxdiag:
![image](https://user-images.githubusercontent.com/1875374/149632026-8dd5a080-28bd-4b0f-8086-05d54f23c5c9.png)

# What I tried
Well, I tried to create a couple of more Windows 10, Windows 11 VMs, but the issue persists in all of them.
I also ran `Update-VMGpuPartitionDriver.ps1`, and it didn't seem to help at all.

Please let me know if there are some logs I can upload. I'm very little versed into Windows, so I'm sure I'm missing something.

# Specs
Intel 10850K
nvidia RTX 3090 with 511.23 driver (I also tried https://developer.nvidia.com/cuda/wsl/download drivers with no luck)
Host OS: Windows 11 (stable)
Guest OS: Windows 11 (stable)

**Comment by jamesstringerparsec** [comment]
The drivers you on the VM are correct, as for the poor performance of your game in the VM, I'm not sure, you can be more specific about the games that performed poorly.
